#!/usr/bin/env node
/**
 * Writes src/config/env.generated.ts, which selects the environment the JS
 * bundle is built for. Run automatically by npm postinstall, the Android
 * Gradle build and the iOS "Bundle React Native code and images" phase.
 *
 * Usage: node scripts/generate-env.js [--env local|staging|prod] [--if-missing]
 *
 * Environment variables:
 *   ATLAS_ENV            environment when --env is not given (default: local)
 *   ATLAS_API_BASE_URL   overrides the API base URL from src/config/environments.json
 *
 * Exits non-zero (failing the build) if the resulting URL is a placeholder or,
 * for staging/prod, not HTTPS.
 */

const fs = require('fs');
const path = require('path');
const {
  ENV_NAMES,
  isEnvName,
  getApiBaseUrlError,
} = require('../src/config/apiBaseUrlRules');

const OUTPUT_PATH = path.join(__dirname, '..', 'src', 'config', 'env.generated.ts');
const ENVIRONMENTS_PATH = path.join(__dirname, '..', 'src', 'config', 'environments.json');

function parseArgs(argv) {
  const args = { env: undefined, ifMissing: false };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--if-missing') {
      args.ifMissing = true;
    } else if (arg === '--env') {
      args.env = argv[i + 1];
      i += 1;
    } else if (arg.startsWith('--env=')) {
      args.env = arg.slice('--env='.length);
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }
  return args;
}

/**
 * Picks the environment and API base URL override and checks every URL the
 * app could end up using for that environment.
 */
function resolveGeneratedEnv({ envArg, processEnv, environments }) {
  const name = envArg || processEnv.ATLAS_ENV || 'local';
  if (!isEnvName(name)) {
    throw new Error(`Unknown ATLAS_ENV "${name}". Expected one of: ${ENV_NAMES.join(', ')}.`);
  }

  const override = processEnv.ATLAS_API_BASE_URL ? processEnv.ATLAS_API_BASE_URL.trim() : '';
  const configured = environments[name].apiBaseUrl;
  const candidates = override
    ? [override]
    : typeof configured === 'string'
      ? [configured]
      : Object.values(configured);

  for (const url of candidates) {
    const error = getApiBaseUrlError(name, url);
    if (error) {
      throw new Error(error);
    }
  }

  return { name, apiBaseUrlOverride: override || null };
}

function quote(value) {
  return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function renderModule(generated) {
  const override = generated.apiBaseUrlOverride === null ? 'null' : quote(generated.apiBaseUrlOverride);
  return [
    '// AUTO-GENERATED by scripts/generate-env.js. Do not edit or commit (gitignored).',
    '// Regenerate with: ATLAS_ENV=<local|staging|prod> npm run env',
    "import type { GeneratedEnv } from './appConfig';",
    '',
    'export const GENERATED_ENV: GeneratedEnv = {',
    `  name: ${quote(generated.name)},`,
    `  apiBaseUrlOverride: ${override},`,
    '};',
    '',
  ].join('\n');
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.ifMissing && fs.existsSync(OUTPUT_PATH)) {
    return;
  }

  const environments = JSON.parse(fs.readFileSync(ENVIRONMENTS_PATH, 'utf8'));
  const generated = resolveGeneratedEnv({
    envArg: args.env,
    processEnv: process.env,
    environments,
  });

  const contents = renderModule(generated);
  const current = fs.existsSync(OUTPUT_PATH) ? fs.readFileSync(OUTPUT_PATH, 'utf8') : null;
  if (current !== contents) {
    fs.writeFileSync(OUTPUT_PATH, contents);
  }
  const urlNote = generated.apiBaseUrlOverride ? ` (API ${generated.apiBaseUrlOverride})` : '';
  console.log(`[atlas-env] ${generated.name}${urlNote} -> ${path.relative(process.cwd(), OUTPUT_PATH)}`);
}

if (require.main === module) {
  try {
    main();
  } catch (error) {
    console.error(`[atlas-env] ${error.message}`);
    process.exit(1);
  }
}

module.exports = { parseArgs, resolveGeneratedEnv, renderModule };
