// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: analytics.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const listCompletedWorkoutDatesSince = `-- name: ListCompletedWorkoutDatesSince :many
SELECT DISTINCT DATE_TRUNC('day', completed_at AT TIME ZONE 'UTC')::date AS completed_date
FROM workouts
WHERE user_id = $1
  AND completed_at IS NOT NULL
  AND completed_at >= $2
ORDER BY completed_date ASC
`

type ListCompletedWorkoutDatesSinceParams struct {
	UserID      uuid.UUID    `json:"user_id"`
	CompletedAt sql.NullTime `json:"completed_at"`
}

func (q *Queries) ListCompletedWorkoutDatesSince(ctx context.Context, arg ListCompletedWorkoutDatesSinceParams) ([]time.Time, error) {
	rows, err := q.db.QueryContext(ctx, listCompletedWorkoutDatesSince, arg.UserID, arg.CompletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []time.Time{}
	for rows.Next() {
		var completed_date time.Time
		if err := rows.Scan(&completed_date); err != nil {
			return nil, err
		}
		items = append(items, completed_date)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedWorkoutIDsSince = `-- name: ListCompletedWorkoutIDsSince :many
SELECT id
FROM workouts
WHERE user_id = $1
  AND completed_at IS NOT NULL
  AND completed_at >= $2
ORDER BY completed_at DESC, id DESC
`

type ListCompletedWorkoutIDsSinceParams struct {
	UserID      uuid.UUID    `json:"user_id"`
	CompletedAt sql.NullTime `json:"completed_at"`
}

func (q *Queries) ListCompletedWorkoutIDsSince(ctx context.Context, arg ListCompletedWorkoutIDsSinceParams) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listCompletedWorkoutIDsSince, arg.UserID, arg.CompletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoreLiftSetsForPR = `-- name: ListCoreLiftSetsForPR :many
SELECT
    e.slug,
    ws.reps,
    ws.weight_kg
FROM workout_sets ws
JOIN workout_exercises we ON we.id = ws.workout_exercise_id
JOIN workouts w ON w.id = we.workout_id
JOIN exercises e ON e.id = we.exercise_id
WHERE w.user_id = $1
  AND e.slug IN ('back-squat', 'bench-press', 'conventional-deadlift')
ORDER BY ws.completed_at DESC, ws.id DESC
`

type ListCoreLiftSetsForPRRow struct {
	Slug     string  `json:"slug"`
	Reps     int32   `json:"reps"`
	WeightKg float64 `json:"weight_kg"`
}

func (q *Queries) ListCoreLiftSetsForPR(ctx context.Context, userID uuid.UUID) ([]ListCoreLiftSetsForPRRow, error) {
	rows, err := q.db.QueryContext(ctx, listCoreLiftSetsForPR, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoreLiftSetsForPRRow{}
	for rows.Next() {
		var i ListCoreLiftSetsForPRRow
		if err := rows.Scan(&i.Slug, &i.Reps, &i.WeightKg); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiftPREventsSince = `-- name: ListLiftPREventsSince :many
WITH scored_sets AS (
    SELECT
        CASE
            WHEN e.slug = 'back-squat' THEN 'squat'
            WHEN e.slug = 'bench-press' THEN 'bench'
            WHEN e.slug = 'conventional-deadlift' THEN 'deadlift'
            ELSE NULL
        END::text AS lift,
        ws.completed_at,
        ws.reps,
        ws.weight_kg,
        (ws.weight_kg * (1.0 + ws.reps::double precision / 30.0))::double precision AS estimated_one_rm_kg,
        ws.id
    FROM workout_sets ws
    JOIN workout_exercises we ON we.id = ws.workout_exercise_id
    JOIN workouts w ON w.id = we.workout_id
    JOIN exercises e ON e.id = we.exercise_id
    WHERE w.user_id = $1
      AND ws.completed_at >= $2
      AND ws.reps > 0
      AND ws.weight_kg >= 0
      AND e.slug IN ('back-squat', 'bench-press', 'conventional-deadlift')
),
events AS (
    SELECT
        lift,
        completed_at,
        reps,
        weight_kg,
        estimated_one_rm_kg,
        MAX(estimated_one_rm_kg) OVER (
            PARTITION BY lift
            ORDER BY completed_at ASC, id ASC
            ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING
        ) AS previous_best_estimated_one_rm_kg
    FROM scored_sets
    WHERE lift IS NOT NULL
)
SELECT
    lift,
    completed_at,
    reps,
    weight_kg,
    estimated_one_rm_kg,
    COALESCE(previous_best_estimated_one_rm_kg, -1.0)::double precision AS previous_best_estimated_one_rm_kg
FROM events
WHERE previous_best_estimated_one_rm_kg IS NULL
   OR estimated_one_rm_kg > previous_best_estimated_one_rm_kg
ORDER BY completed_at DESC, lift ASC
`

type ListLiftPREventsSinceParams struct {
	UserID      uuid.UUID `json:"user_id"`
	CompletedAt time.Time `json:"completed_at"`
}

type ListLiftPREventsSinceRow struct {
	Lift                         string    `json:"lift"`
	CompletedAt                  time.Time `json:"completed_at"`
	Reps                         int32     `json:"reps"`
	WeightKg                     float64   `json:"weight_kg"`
	EstimatedOneRmKg             float64   `json:"estimated_one_rm_kg"`
	PreviousBestEstimatedOneRmKg float64   `json:"previous_best_estimated_one_rm_kg"`
}

// Epley estimated 1RM formula: estimated_1RM = weight_kg * (1 + reps / 30)
func (q *Queries) ListLiftPREventsSince(ctx context.Context, arg ListLiftPREventsSinceParams) ([]ListLiftPREventsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listLiftPREventsSince, arg.UserID, arg.CompletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLiftPREventsSinceRow{}
	for rows.Next() {
		var i ListLiftPREventsSinceRow
		if err := rows.Scan(
			&i.Lift,
			&i.CompletedAt,
			&i.Reps,
			&i.WeightKg,
			&i.EstimatedOneRmKg,
			&i.PreviousBestEstimatedOneRmKg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMainLiftEstimatedOneRM = `-- name: ListMainLiftEstimatedOneRM :many
WITH scored_sets AS (
    SELECT
        CASE
            WHEN e.slug = 'back-squat' THEN 'squat'
            WHEN e.slug = 'bench-press' THEN 'bench'
            WHEN e.slug = 'conventional-deadlift' THEN 'deadlift'
            ELSE NULL
        END::text AS lift,
        ws.completed_at,
        ws.reps,
        ws.weight_kg,
        (ws.weight_kg * (1.0 + ws.reps::double precision / 30.0))::double precision AS estimated_one_rm_kg,
        ws.id
    FROM workout_sets ws
    JOIN workout_exercises we ON we.id = ws.workout_exercise_id
    JOIN workouts w ON w.id = we.workout_id
    JOIN exercises e ON e.id = we.exercise_id
    WHERE w.user_id = $1
      AND ws.reps > 0
      AND ws.weight_kg >= 0
      AND e.slug IN ('back-squat', 'bench-press', 'conventional-deadlift')
),
ranked AS (
    SELECT
        lift,
        completed_at,
        reps,
        weight_kg,
        estimated_one_rm_kg,
        ROW_NUMBER() OVER (
            PARTITION BY lift
            ORDER BY estimated_one_rm_kg DESC, completed_at DESC, id DESC
        ) AS rank_index
    FROM scored_sets
    WHERE lift IS NOT NULL
)
SELECT
    lift,
    completed_at,
    reps,
    weight_kg,
    estimated_one_rm_kg
FROM ranked
WHERE rank_index = 1
ORDER BY lift ASC
`

type ListMainLiftEstimatedOneRMRow struct {
	Lift             string    `json:"lift"`
	CompletedAt      time.Time `json:"completed_at"`
	Reps             int32     `json:"reps"`
	WeightKg         float64   `json:"weight_kg"`
	EstimatedOneRmKg float64   `json:"estimated_one_rm_kg"`
}

// Epley estimated 1RM formula: estimated_1RM = weight_kg * (1 + reps / 30)
func (q *Queries) ListMainLiftEstimatedOneRM(ctx context.Context, userID uuid.UUID) ([]ListMainLiftEstimatedOneRMRow, error) {
	rows, err := q.db.QueryContext(ctx, listMainLiftEstimatedOneRM, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMainLiftEstimatedOneRMRow{}
	for rows.Next() {
		var i ListMainLiftEstimatedOneRMRow
		if err := rows.Scan(
			&i.Lift,
			&i.CompletedAt,
			&i.Reps,
			&i.WeightKg,
			&i.EstimatedOneRmKg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNutritionProteinCheckinsSinceDate = `-- name: ListNutritionProteinCheckinsSinceDate :many
SELECT date, hit_protein
FROM nutrition_daily_checkins
WHERE user_id = $1
  AND date >= $2
ORDER BY date ASC
`

type ListNutritionProteinCheckinsSinceDateParams struct {
	UserID uuid.UUID `json:"user_id"`
	Date   time.Time `json:"date"`
}

type ListNutritionProteinCheckinsSinceDateRow struct {
	Date       time.Time `json:"date"`
	HitProtein bool      `json:"hit_protein"`
}

func (q *Queries) ListNutritionProteinCheckinsSinceDate(ctx context.Context, arg ListNutritionProteinCheckinsSinceDateParams) ([]ListNutritionProteinCheckinsSinceDateRow, error) {
	rows, err := q.db.QueryContext(ctx, listNutritionProteinCheckinsSinceDate, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNutritionProteinCheckinsSinceDateRow{}
	for rows.Next() {
		var i ListNutritionProteinCheckinsSinceDateRow
		if err := rows.Scan(&i.Date, &i.HitProtein); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProteinHitDatesSinceDate = `-- name: ListProteinHitDatesSinceDate :many
SELECT date AS hit_date
FROM nutrition_daily_checkins
WHERE user_id = $1
  AND date >= $2
  AND hit_protein = TRUE
ORDER BY hit_date ASC
`

type ListProteinHitDatesSinceDateParams struct {
	UserID uuid.UUID `json:"user_id"`
	Date   time.Time `json:"date"`
}

func (q *Queries) ListProteinHitDatesSinceDate(ctx context.Context, arg ListProteinHitDatesSinceDateParams) ([]time.Time, error) {
	rows, err := q.db.QueryContext(ctx, listProteinHitDatesSinceDate, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []time.Time{}
	for rows.Next() {
		var hit_date time.Time
		if err := rows.Scan(&hit_date); err != nil {
			return nil, err
		}
		items = append(items, hit_date)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadinessCheckinsSinceDate = `-- name: ListReadinessCheckinsSinceDate :many
SELECT date, energy_level, sleep_quality, stress_level, readiness_score
FROM readiness_checkins
WHERE user_id = $1
  AND date >= $2
ORDER BY date ASC
`

type ListReadinessCheckinsSinceDateParams struct {
	UserID uuid.UUID `json:"user_id"`
	Date   time.Time `json:"date"`
}

type ListReadinessCheckinsSinceDateRow struct {
	Date           time.Time `json:"date"`
	EnergyLevel    int32     `json:"energy_level"`
	SleepQuality   int32     `json:"sleep_quality"`
	StressLevel    int32     `json:"stress_level"`
	ReadinessScore float64   `json:"readiness_score"`
}

func (q *Queries) ListReadinessCheckinsSinceDate(ctx context.Context, arg ListReadinessCheckinsSinceDateParams) ([]ListReadinessCheckinsSinceDateRow, error) {
	rows, err := q.db.QueryContext(ctx, listReadinessCheckinsSinceDate, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReadinessCheckinsSinceDateRow{}
	for rows.Next() {
		var i ListReadinessCheckinsSinceDateRow
		if err := rows.Scan(
			&i.Date,
			&i.EnergyLevel,
			&i.SleepQuality,
			&i.StressLevel,
			&i.ReadinessScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeeklyMuscleGroupVolumeSince = `-- name: ListWeeklyMuscleGroupVolumeSince :many
WITH set_volume AS (
    SELECT
        ws.id AS workout_set_id,
        DATE_TRUNC('week', ws.completed_at AT TIME ZONE 'UTC')::date AS week_start_date,
        (ws.reps::double precision * ws.weight_kg) AS set_volume_kg,
        e.primary_muscles,
        e.secondary_muscles
    FROM workout_sets ws
    JOIN workout_exercises we ON we.id = ws.workout_exercise_id
    JOIN workouts w ON w.id = we.workout_id
    JOIN exercises e ON e.id = we.exercise_id
    WHERE w.user_id = $1
      AND ws.completed_at >= $2
      AND ws.reps > 0
      AND ws.weight_kg >= 0
),
expanded AS (
    SELECT
        sv.week_start_date,
        LOWER(TRIM(muscle_map.muscle_group)) AS muscle_group,
        sv.set_volume_kg,
        muscle_map.coefficient,
        (
            COALESCE(jsonb_array_length(sv.primary_muscles), 0)::double precision
            + COALESCE(jsonb_array_length(sv.secondary_muscles), 0)::double precision * 0.5
        ) AS coefficient_total
    FROM set_volume sv
    CROSS JOIN LATERAL (
        SELECT primary_muscle.value AS muscle_group, 1.0::double precision AS coefficient
        FROM jsonb_array_elements_text(sv.primary_muscles) AS primary_muscle(value)
        UNION ALL
        SELECT secondary_muscle.value AS muscle_group, 0.5::double precision AS coefficient
        FROM jsonb_array_elements_text(sv.secondary_muscles) AS secondary_muscle(value)
    ) AS muscle_map
)
SELECT
    week_start_date,
    muscle_group,
    SUM(
        CASE
            WHEN coefficient_total <= 0 THEN 0
            ELSE set_volume_kg * (coefficient / coefficient_total)
        END
    )::double precision AS volume_kg
FROM expanded
WHERE muscle_group <> ''
GROUP BY week_start_date, muscle_group
ORDER BY week_start_date DESC, volume_kg DESC, muscle_group ASC
`

type ListWeeklyMuscleGroupVolumeSinceParams struct {
	UserID      uuid.UUID `json:"user_id"`
	CompletedAt time.Time `json:"completed_at"`
}

type ListWeeklyMuscleGroupVolumeSinceRow struct {
	WeekStartDate time.Time `json:"week_start_date"`
	MuscleGroup   string    `json:"muscle_group"`
	VolumeKg      float64   `json:"volume_kg"`
}

// Muscle group allocation uses normalized coefficients:
// primary muscles = 1.0 each, secondary muscles = 0.5 each.
func (q *Queries) ListWeeklyMuscleGroupVolumeSince(ctx context.Context, arg ListWeeklyMuscleGroupVolumeSinceParams) ([]ListWeeklyMuscleGroupVolumeSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listWeeklyMuscleGroupVolumeSince, arg.UserID, arg.CompletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWeeklyMuscleGroupVolumeSinceRow{}
	for rows.Next() {
		var i ListWeeklyMuscleGroupVolumeSinceRow
		if err := rows.Scan(&i.WeekStartDate, &i.MuscleGroup, &i.VolumeKg); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeightTrendPointsSinceDate = `-- name: ListWeightTrendPointsSinceDate :many
SELECT date, weight_kg
FROM user_weight_entries
WHERE user_id = $1
  AND date >= $2
ORDER BY date ASC
`

type ListWeightTrendPointsSinceDateParams struct {
	UserID uuid.UUID `json:"user_id"`
	Date   time.Time `json:"date"`
}

type ListWeightTrendPointsSinceDateRow struct {
	Date     time.Time `json:"date"`
	WeightKg float64   `json:"weight_kg"`
}

func (q *Queries) ListWeightTrendPointsSinceDate(ctx context.Context, arg ListWeightTrendPointsSinceDateParams) ([]ListWeightTrendPointsSinceDateRow, error) {
	rows, err := q.db.QueryContext(ctx, listWeightTrendPointsSinceDate, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWeightTrendPointsSinceDateRow{}
	for rows.Next() {
		var i ListWeightTrendPointsSinceDateRow
		if err := rows.Scan(&i.Date, &i.WeightKg); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutSetMetricsSince = `-- name: ListWorkoutSetMetricsSince :many
SELECT
    e.movement_pattern,
    ws.reps,
    ws.weight_kg
FROM workout_sets ws
JOIN workout_exercises we ON we.id = ws.workout_exercise_id
JOIN workouts w ON w.id = we.workout_id
JOIN exercises e ON e.id = we.exercise_id
WHERE w.user_id = $1
  AND ws.completed_at >= $2
ORDER BY ws.completed_at DESC, ws.id DESC
`

type ListWorkoutSetMetricsSinceParams struct {
	UserID      uuid.UUID `json:"user_id"`
	CompletedAt time.Time `json:"completed_at"`
}

type ListWorkoutSetMetricsSinceRow struct {
	MovementPattern string  `json:"movement_pattern"`
	Reps            int32   `json:"reps"`
	WeightKg        float64 `json:"weight_kg"`
}

func (q *Queries) ListWorkoutSetMetricsSince(ctx context.Context, arg ListWorkoutSetMetricsSinceParams) ([]ListWorkoutSetMetricsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkoutSetMetricsSince, arg.UserID, arg.CompletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkoutSetMetricsSinceRow{}
	for rows.Next() {
		var i ListWorkoutSetMetricsSinceRow
		if err := rows.Scan(&i.MovementPattern, &i.Reps, &i.WeightKg); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
