// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: community.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addCrewMember = `-- name: AddCrewMember :one
INSERT INTO crew_members (
    crew_id,
    user_id,
    role
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (crew_id, user_id)
DO UPDATE SET
    role = crew_members.role
RETURNING crew_id, user_id, role, joined_at
`

type AddCrewMemberParams struct {
	CrewID uuid.UUID `json:"crew_id"`
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

func (q *Queries) AddCrewMember(ctx context.Context, arg AddCrewMemberParams) (CrewMember, error) {
	row := q.db.QueryRowContext(ctx, addCrewMember, arg.CrewID, arg.UserID, arg.Role)
	var i CrewMember
	err := row.Scan(
		&i.CrewID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const createCrew = `-- name: CreateCrew :one
INSERT INTO crews (
    name,
    description,
    created_by_user_id,
    is_private,
    shared_plan_url,
    shared_habits_url
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING
    id,
    name,
    description,
    created_by_user_id,
    is_private,
    shared_plan_url,
    shared_habits_url,
    created_at,
    updated_at
`

type CreateCrewParams struct {
	Name            string         `json:"name"`
	Description     string         `json:"description"`
	CreatedByUserID uuid.UUID      `json:"created_by_user_id"`
	IsPrivate       bool           `json:"is_private"`
	SharedPlanUrl   sql.NullString `json:"shared_plan_url"`
	SharedHabitsUrl sql.NullString `json:"shared_habits_url"`
}

func (q *Queries) CreateCrew(ctx context.Context, arg CreateCrewParams) (Crew, error) {
	row := q.db.QueryRowContext(ctx, createCrew,
		arg.Name,
		arg.Description,
		arg.CreatedByUserID,
		arg.IsPrivate,
		arg.SharedPlanUrl,
		arg.SharedHabitsUrl,
	)
	var i Crew
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedByUserID,
		&i.IsPrivate,
		&i.SharedPlanUrl,
		&i.SharedHabitsUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCrewInvite = `-- name: CreateCrewInvite :one
INSERT INTO crew_invites (
    crew_id,
    invite_code,
    invited_by_user_id,
    max_uses,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING
    id,
    crew_id,
    invite_code,
    invited_by_user_id,
    max_uses,
    uses_count,
    expires_at,
    revoked_at,
    created_at
`

type CreateCrewInviteParams struct {
	CrewID          uuid.UUID    `json:"crew_id"`
	InviteCode      string       `json:"invite_code"`
	InvitedByUserID uuid.UUID    `json:"invited_by_user_id"`
	MaxUses         int32        `json:"max_uses"`
	ExpiresAt       sql.NullTime `json:"expires_at"`
}

func (q *Queries) CreateCrewInvite(ctx context.Context, arg CreateCrewInviteParams) (CrewInvite, error) {
	row := q.db.QueryRowContext(ctx, createCrewInvite,
		arg.CrewID,
		arg.InviteCode,
		arg.InvitedByUserID,
		arg.MaxUses,
		arg.ExpiresAt,
	)
	var i CrewInvite
	err := row.Scan(
		&i.ID,
		&i.CrewID,
		&i.InviteCode,
		&i.InvitedByUserID,
		&i.MaxUses,
		&i.UsesCount,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveCrewInviteByCode = `-- name: GetActiveCrewInviteByCode :one
SELECT
    id,
    crew_id,
    invite_code,
    invited_by_user_id,
    max_uses,
    uses_count,
    expires_at,
    revoked_at,
    created_at
FROM crew_invites
WHERE invite_code = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > NOW())
  AND uses_count < max_uses
LIMIT 1
`

func (q *Queries) GetActiveCrewInviteByCode(ctx context.Context, inviteCode string) (CrewInvite, error) {
	row := q.db.QueryRowContext(ctx, getActiveCrewInviteByCode, inviteCode)
	var i CrewInvite
	err := row.Scan(
		&i.ID,
		&i.CrewID,
		&i.InviteCode,
		&i.InvitedByUserID,
		&i.MaxUses,
		&i.UsesCount,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCoachSessionByID = `-- name: GetCoachSessionByID :one
SELECT
    id,
    crew_id,
    title,
    description,
    coach_name,
    duration_seconds,
    required_tier,
    published,
    created_at,
    updated_at
FROM coach_sessions
WHERE id = $1
  AND published = TRUE
LIMIT 1
`

func (q *Queries) GetCoachSessionByID(ctx context.Context, id uuid.UUID) (CoachSession, error) {
	row := q.db.QueryRowContext(ctx, getCoachSessionByID, id)
	var i CoachSession
	err := row.Scan(
		&i.ID,
		&i.CrewID,
		&i.Title,
		&i.Description,
		&i.CoachName,
		&i.DurationSeconds,
		&i.RequiredTier,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoachSessionByIDForUser = `-- name: GetCoachSessionByIDForUser :one
SELECT
    cs.id,
    cs.crew_id,
    cs.title,
    cs.description,
    cs.coach_name,
    cs.duration_seconds,
    cs.required_tier,
    cs.published,
    cs.created_at,
    cs.updated_at,
    c.name AS crew_name
FROM coach_sessions cs
JOIN crews c ON c.id = cs.crew_id
JOIN crew_members cm ON cm.crew_id = cs.crew_id
WHERE cs.id = $1
  AND cm.user_id = $2
  AND cs.published = TRUE
LIMIT 1
`

type GetCoachSessionByIDForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetCoachSessionByIDForUserRow struct {
	ID              uuid.UUID `json:"id"`
	CrewID          uuid.UUID `json:"crew_id"`
	Title           string    `json:"title"`
	Description     string    `json:"description"`
	CoachName       string    `json:"coach_name"`
	DurationSeconds int32     `json:"duration_seconds"`
	RequiredTier    string    `json:"required_tier"`
	Published       bool      `json:"published"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	CrewName        string    `json:"crew_name"`
}

func (q *Queries) GetCoachSessionByIDForUser(ctx context.Context, arg GetCoachSessionByIDForUserParams) (GetCoachSessionByIDForUserRow, error) {
	row := q.db.QueryRowContext(ctx, getCoachSessionByIDForUser, arg.ID, arg.UserID)
	var i GetCoachSessionByIDForUserRow
	err := row.Scan(
		&i.ID,
		&i.CrewID,
		&i.Title,
		&i.Description,
		&i.CoachName,
		&i.DurationSeconds,
		&i.RequiredTier,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CrewName,
	)
	return i, err
}

const getCrewByID = `-- name: GetCrewByID :one
SELECT
    id,
    name,
    description,
    created_by_user_id,
    is_private,
    shared_plan_url,
    shared_habits_url,
    created_at,
    updated_at
FROM crews
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCrewByID(ctx context.Context, id uuid.UUID) (Crew, error) {
	row := q.db.QueryRowContext(ctx, getCrewByID, id)
	var i Crew
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedByUserID,
		&i.IsPrivate,
		&i.SharedPlanUrl,
		&i.SharedHabitsUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCrewByIDForUser = `-- name: GetCrewByIDForUser :one
SELECT
    c.id,
    c.name,
    c.description,
    c.created_by_user_id,
    c.is_private,
    c.shared_plan_url,
    c.shared_habits_url,
    c.created_at,
    c.updated_at,
    cm.role AS my_role,
    COUNT(cm_all.user_id)::int AS member_count
FROM crews c
JOIN crew_members cm ON cm.crew_id = c.id
JOIN crew_members cm_all ON cm_all.crew_id = c.id
WHERE c.id = $1
  AND cm.user_id = $2
GROUP BY
    c.id,
    c.name,
    c.description,
    c.created_by_user_id,
    c.is_private,
    c.shared_plan_url,
    c.shared_habits_url,
    c.created_at,
    c.updated_at,
    cm.role
LIMIT 1
`

type GetCrewByIDForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetCrewByIDForUserRow struct {
	ID              uuid.UUID      `json:"id"`
	Name            string         `json:"name"`
	Description     string         `json:"description"`
	CreatedByUserID uuid.UUID      `json:"created_by_user_id"`
	IsPrivate       bool           `json:"is_private"`
	SharedPlanUrl   sql.NullString `json:"shared_plan_url"`
	SharedHabitsUrl sql.NullString `json:"shared_habits_url"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	MyRole          string         `json:"my_role"`
	MemberCount     int32          `json:"member_count"`
}

func (q *Queries) GetCrewByIDForUser(ctx context.Context, arg GetCrewByIDForUserParams) (GetCrewByIDForUserRow, error) {
	row := q.db.QueryRowContext(ctx, getCrewByIDForUser, arg.ID, arg.UserID)
	var i GetCrewByIDForUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedByUserID,
		&i.IsPrivate,
		&i.SharedPlanUrl,
		&i.SharedHabitsUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MyRole,
		&i.MemberCount,
	)
	return i, err
}

const getCrewMemberByCrewIDAndUserID = `-- name: GetCrewMemberByCrewIDAndUserID :one
SELECT crew_id, user_id, role, joined_at
FROM crew_members
WHERE crew_id = $1
  AND user_id = $2
LIMIT 1
`

type GetCrewMemberByCrewIDAndUserIDParams struct {
	CrewID uuid.UUID `json:"crew_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetCrewMemberByCrewIDAndUserID(ctx context.Context, arg GetCrewMemberByCrewIDAndUserIDParams) (CrewMember, error) {
	row := q.db.QueryRowContext(ctx, getCrewMemberByCrewIDAndUserID, arg.CrewID, arg.UserID)
	var i CrewMember
	err := row.Scan(
		&i.CrewID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const incrementCrewInviteUse = `-- name: IncrementCrewInviteUse :one
UPDATE crew_invites
SET uses_count = uses_count + 1
WHERE id = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > NOW())
  AND uses_count < max_uses
RETURNING
    id,
    crew_id,
    invite_code,
    invited_by_user_id,
    max_uses,
    uses_count,
    expires_at,
    revoked_at,
    created_at
`

func (q *Queries) IncrementCrewInviteUse(ctx context.Context, id uuid.UUID) (CrewInvite, error) {
	row := q.db.QueryRowContext(ctx, incrementCrewInviteUse, id)
	var i CrewInvite
	err := row.Scan(
		&i.ID,
		&i.CrewID,
		&i.InviteCode,
		&i.InvitedByUserID,
		&i.MaxUses,
		&i.UsesCount,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCoachSessionAssetsBySessionID = `-- name: ListCoachSessionAssetsBySessionID :many
SELECT
    id,
    coach_session_id,
    asset_type,
    storage_key,
    mime_type,
    created_at
FROM coach_session_assets
WHERE coach_session_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListCoachSessionAssetsBySessionID(ctx context.Context, coachSessionID uuid.UUID) ([]CoachSessionAsset, error) {
	rows, err := q.db.QueryContext(ctx, listCoachSessionAssetsBySessionID, coachSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoachSessionAsset{}
	for rows.Next() {
		var i CoachSessionAsset
		if err := rows.Scan(
			&i.ID,
			&i.CoachSessionID,
			&i.AssetType,
			&i.StorageKey,
			&i.MimeType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoachSessionsByUserID = `-- name: ListCoachSessionsByUserID :many
SELECT
    cs.id,
    cs.crew_id,
    cs.title,
    cs.description,
    cs.coach_name,
    cs.duration_seconds,
    cs.required_tier,
    cs.published,
    cs.created_at,
    cs.updated_at,
    c.name AS crew_name
FROM coach_sessions cs
JOIN crews c ON c.id = cs.crew_id
JOIN crew_members cm ON cm.crew_id = cs.crew_id
WHERE cm.user_id = $1
  AND cs.published = TRUE
ORDER BY cs.created_at DESC
`

type ListCoachSessionsByUserIDRow struct {
	ID              uuid.UUID `json:"id"`
	CrewID          uuid.UUID `json:"crew_id"`
	Title           string    `json:"title"`
	Description     string    `json:"description"`
	CoachName       string    `json:"coach_name"`
	DurationSeconds int32     `json:"duration_seconds"`
	RequiredTier    string    `json:"required_tier"`
	Published       bool      `json:"published"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	CrewName        string    `json:"crew_name"`
}

func (q *Queries) ListCoachSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]ListCoachSessionsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listCoachSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoachSessionsByUserIDRow{}
	for rows.Next() {
		var i ListCoachSessionsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CrewID,
			&i.Title,
			&i.Description,
			&i.CoachName,
			&i.DurationSeconds,
			&i.RequiredTier,
			&i.Published,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CrewName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCrewMembersByCrewID = `-- name: ListCrewMembersByCrewID :many
SELECT
    cm.crew_id,
    cm.user_id,
    cm.role,
    cm.joined_at,
    u.email,
    COALESCE(up.display_name, '') AS display_name
FROM crew_members cm
JOIN users u ON u.id = cm.user_id
LEFT JOIN user_profiles up ON up.user_id = cm.user_id
WHERE cm.crew_id = $1
ORDER BY
    CASE WHEN cm.role = 'owner' THEN 0 ELSE 1 END,
    cm.joined_at ASC
`

type ListCrewMembersByCrewIDRow struct {
	CrewID      uuid.UUID `json:"crew_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
	JoinedAt    time.Time `json:"joined_at"`
	Email       string    `json:"email"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) ListCrewMembersByCrewID(ctx context.Context, crewID uuid.UUID) ([]ListCrewMembersByCrewIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listCrewMembersByCrewID, crewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCrewMembersByCrewIDRow{}
	for rows.Next() {
		var i ListCrewMembersByCrewIDRow
		if err := rows.Scan(
			&i.CrewID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Email,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCrewsByUserID = `-- name: ListCrewsByUserID :many
SELECT
    c.id,
    c.name,
    c.description,
    c.created_by_user_id,
    c.is_private,
    c.shared_plan_url,
    c.shared_habits_url,
    c.created_at,
    c.updated_at,
    cm.role AS my_role,
    COUNT(cm_all.user_id)::int AS member_count
FROM crew_members cm
JOIN crews c ON c.id = cm.crew_id
JOIN crew_members cm_all ON cm_all.crew_id = c.id
WHERE cm.user_id = $1
GROUP BY
    c.id,
    c.name,
    c.description,
    c.created_by_user_id,
    c.is_private,
    c.shared_plan_url,
    c.shared_habits_url,
    c.created_at,
    c.updated_at,
    cm.role
ORDER BY c.created_at DESC
`

type ListCrewsByUserIDRow struct {
	ID              uuid.UUID      `json:"id"`
	Name            string         `json:"name"`
	Description     string         `json:"description"`
	CreatedByUserID uuid.UUID      `json:"created_by_user_id"`
	IsPrivate       bool           `json:"is_private"`
	SharedPlanUrl   sql.NullString `json:"shared_plan_url"`
	SharedHabitsUrl sql.NullString `json:"shared_habits_url"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	MyRole          string         `json:"my_role"`
	MemberCount     int32          `json:"member_count"`
}

func (q *Queries) ListCrewsByUserID(ctx context.Context, userID uuid.UUID) ([]ListCrewsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listCrewsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCrewsByUserIDRow{}
	for rows.Next() {
		var i ListCrewsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedByUserID,
			&i.IsPrivate,
			&i.SharedPlanUrl,
			&i.SharedHabitsUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MyRole,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCueTimelineBySessionID = `-- name: ListCueTimelineBySessionID :many
SELECT
    id,
    coach_session_id,
    cue_index,
    start_ms,
    end_ms,
    cue_text,
    biomechanics_exercise_id,
    biomechanics_definition_type,
    biomechanics_definition_key,
    created_at
FROM cue_timeline
WHERE coach_session_id = $1
ORDER BY cue_index ASC, start_ms ASC, id ASC
`

func (q *Queries) ListCueTimelineBySessionID(ctx context.Context, coachSessionID uuid.UUID) ([]CueTimeline, error) {
	rows, err := q.db.QueryContext(ctx, listCueTimelineBySessionID, coachSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CueTimeline{}
	for rows.Next() {
		var i CueTimeline
		if err := rows.Scan(
			&i.ID,
			&i.CoachSessionID,
			&i.CueIndex,
			&i.StartMs,
			&i.EndMs,
			&i.CueText,
			&i.BiomechanicsExerciseID,
			&i.BiomechanicsDefinitionType,
			&i.BiomechanicsDefinitionKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
