// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: consents.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const hasActiveConsent = `-- name: HasActiveConsent :one
SELECT EXISTS (
    SELECT 1
    FROM consents
    WHERE user_id = $1
      AND consent_type = $2
      AND revoked_at IS NULL
) AS has_active_consent
`

type HasActiveConsentParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ConsentType string    `json:"consent_type"`
}

func (q *Queries) HasActiveConsent(ctx context.Context, arg HasActiveConsentParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasActiveConsent, arg.UserID, arg.ConsentType)
	var has_active_consent bool
	err := row.Scan(&has_active_consent)
	return has_active_consent, err
}

const listConsentsByUserID = `-- name: ListConsentsByUserID :many
SELECT id, user_id, consent_type, granted_at, revoked_at, metadata_json
FROM consents
WHERE user_id = $1
ORDER BY consent_type ASC
`

func (q *Queries) ListConsentsByUserID(ctx context.Context, userID uuid.UUID) ([]Consent, error) {
	rows, err := q.db.QueryContext(ctx, listConsentsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Consent{}
	for rows.Next() {
		var i Consent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ConsentType,
			&i.GrantedAt,
			&i.RevokedAt,
			&i.MetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeConsent = `-- name: RevokeConsent :one
UPDATE consents
SET revoked_at = NOW()
WHERE user_id = $1
  AND consent_type = $2
  AND revoked_at IS NULL
RETURNING id, user_id, consent_type, granted_at, revoked_at, metadata_json
`

type RevokeConsentParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ConsentType string    `json:"consent_type"`
}

func (q *Queries) RevokeConsent(ctx context.Context, arg RevokeConsentParams) (Consent, error) {
	row := q.db.QueryRowContext(ctx, revokeConsent, arg.UserID, arg.ConsentType)
	var i Consent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConsentType,
		&i.GrantedAt,
		&i.RevokedAt,
		&i.MetadataJson,
	)
	return i, err
}

const upsertConsent = `-- name: UpsertConsent :one
INSERT INTO consents (
    user_id,
    consent_type,
    granted_at,
    revoked_at,
    metadata_json
) VALUES (
    $1,
    $2,
    NOW(),
    NULL,
    $3
)
ON CONFLICT (user_id, consent_type)
DO UPDATE SET
    granted_at = NOW(),
    revoked_at = NULL,
    metadata_json = EXCLUDED.metadata_json
RETURNING id, user_id, consent_type, granted_at, revoked_at, metadata_json
`

type UpsertConsentParams struct {
	UserID       uuid.UUID       `json:"user_id"`
	ConsentType  string          `json:"consent_type"`
	MetadataJson json.RawMessage `json:"metadata_json"`
}

func (q *Queries) UpsertConsent(ctx context.Context, arg UpsertConsentParams) (Consent, error) {
	row := q.db.QueryRowContext(ctx, upsertConsent, arg.UserID, arg.ConsentType, arg.MetadataJson)
	var i Consent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConsentType,
		&i.GrantedAt,
		&i.RevokedAt,
		&i.MetadataJson,
	)
	return i, err
}
