// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: events.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createAppEvent = `-- name: CreateAppEvent :one
INSERT INTO app_events (
    user_id,
    event_name,
    event_time,
    properties_json,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    NOW()
)
RETURNING id, user_id, event_name, event_time, properties_json, created_at
`

type CreateAppEventParams struct {
	UserID         uuid.NullUUID   `json:"user_id"`
	EventName      string          `json:"event_name"`
	EventTime      time.Time       `json:"event_time"`
	PropertiesJson json.RawMessage `json:"properties_json"`
}

func (q *Queries) CreateAppEvent(ctx context.Context, arg CreateAppEventParams) (AppEvent, error) {
	row := q.db.QueryRowContext(ctx, createAppEvent,
		arg.UserID,
		arg.EventName,
		arg.EventTime,
		arg.PropertiesJson,
	)
	var i AppEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventName,
		&i.EventTime,
		&i.PropertiesJson,
		&i.CreatedAt,
	)
	return i, err
}
