// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: exercises.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getExerciseByID = `-- name: GetExerciseByID :one
SELECT id, slug, name, primary_muscle_group, secondary_muscles_json, movement_pattern, movement_pattern_taxonomy, primary_muscles, secondary_muscles, contraindications, contraindication_tags, equipment_json, equipment_requirements, difficulty, description, created_at
FROM exercises
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetExerciseByID(ctx context.Context, id uuid.UUID) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, getExerciseByID, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.PrimaryMuscleGroup,
		&i.SecondaryMusclesJson,
		&i.MovementPattern,
		&i.MovementPatternTaxonomy,
		&i.PrimaryMuscles,
		&i.SecondaryMuscles,
		&i.Contraindications,
		&i.ContraindicationTags,
		&i.EquipmentJson,
		&i.EquipmentRequirements,
		&i.Difficulty,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listExerciseCandidatesForSubstitution = `-- name: ListExerciseCandidatesForSubstitution :many
SELECT id, slug, name, primary_muscle_group, secondary_muscles_json, movement_pattern, movement_pattern_taxonomy, primary_muscles, secondary_muscles, contraindications, contraindication_tags, equipment_json, equipment_requirements, difficulty, description, created_at
FROM exercises
WHERE id <> $1
ORDER BY name ASC
`

func (q *Queries) ListExerciseCandidatesForSubstitution(ctx context.Context, exerciseID uuid.UUID) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, listExerciseCandidatesForSubstitution, exerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exercise{}
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.PrimaryMuscleGroup,
			&i.SecondaryMusclesJson,
			&i.MovementPattern,
			&i.MovementPatternTaxonomy,
			&i.PrimaryMuscles,
			&i.SecondaryMuscles,
			&i.Contraindications,
			&i.ContraindicationTags,
			&i.EquipmentJson,
			&i.EquipmentRequirements,
			&i.Difficulty,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExerciseMediaByExerciseID = `-- name: ListExerciseMediaByExerciseID :many
SELECT id, exercise_id, media_type, uri, thumbnail_uri, duration_seconds, created_at
FROM exercise_media
WHERE exercise_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListExerciseMediaByExerciseID(ctx context.Context, exerciseID uuid.UUID) ([]ExerciseMedium, error) {
	rows, err := q.db.QueryContext(ctx, listExerciseMediaByExerciseID, exerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExerciseMedium{}
	for rows.Next() {
		var i ExerciseMedium
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseID,
			&i.MediaType,
			&i.Uri,
			&i.ThumbnailUri,
			&i.DurationSeconds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExercises = `-- name: ListExercises :many
SELECT id, slug, name, primary_muscle_group, secondary_muscles_json, movement_pattern, movement_pattern_taxonomy, primary_muscles, secondary_muscles, contraindications, contraindication_tags, equipment_json, equipment_requirements, difficulty, description, created_at
FROM exercises
WHERE ($1::text = '' OR name ILIKE '%' || $1 || '%' OR slug ILIKE '%' || $1 || '%' OR description ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR equipment_json ? $2)
  AND ($3::text = '' OR movement_pattern = $3)
ORDER BY name ASC
`

type ListExercisesParams struct {
	Query     string `json:"query"`
	Equipment string `json:"equipment"`
	Pattern   string `json:"pattern"`
}

func (q *Queries) ListExercises(ctx context.Context, arg ListExercisesParams) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, listExercises, arg.Query, arg.Equipment, arg.Pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exercise{}
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.PrimaryMuscleGroup,
			&i.SecondaryMusclesJson,
			&i.MovementPattern,
			&i.MovementPatternTaxonomy,
			&i.PrimaryMuscles,
			&i.SecondaryMuscles,
			&i.Contraindications,
			&i.ContraindicationTags,
			&i.EquipmentJson,
			&i.EquipmentRequirements,
			&i.Difficulty,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExercise = `-- name: UpsertExercise :one
INSERT INTO exercises (
    id,
    slug,
    name,
    primary_muscle_group,
    secondary_muscles_json,
    movement_pattern,
    movement_pattern_taxonomy,
    primary_muscles,
    secondary_muscles,
    contraindications,
    contraindication_tags,
    equipment_json,
    equipment_requirements,
    difficulty,
    description
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    jsonb_build_array($6::text),
    $7,
    $8,
    $9,
    $9,
    $10,
    $10,
    $11,
    $12
)
ON CONFLICT (slug)
DO UPDATE SET
    name = EXCLUDED.name,
    primary_muscle_group = EXCLUDED.primary_muscle_group,
    secondary_muscles_json = EXCLUDED.secondary_muscles_json,
    movement_pattern = EXCLUDED.movement_pattern,
    movement_pattern_taxonomy = EXCLUDED.movement_pattern_taxonomy,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    contraindications = EXCLUDED.contraindications,
    contraindication_tags = EXCLUDED.contraindication_tags,
    equipment_json = EXCLUDED.equipment_json,
    equipment_requirements = EXCLUDED.equipment_requirements,
    difficulty = EXCLUDED.difficulty,
    description = EXCLUDED.description
RETURNING id, slug, name, primary_muscle_group, secondary_muscles_json, movement_pattern, movement_pattern_taxonomy, primary_muscles, secondary_muscles, contraindications, contraindication_tags, equipment_json, equipment_requirements, difficulty, description, created_at
`

type UpsertExerciseParams struct {
	ID                   uuid.UUID       `json:"id"`
	Slug                 string          `json:"slug"`
	Name                 string          `json:"name"`
	PrimaryMuscleGroup   string          `json:"primary_muscle_group"`
	SecondaryMusclesJson json.RawMessage `json:"secondary_muscles_json"`
	MovementPattern      string          `json:"movement_pattern"`
	PrimaryMuscles       json.RawMessage `json:"primary_muscles"`
	SecondaryMuscles     json.RawMessage `json:"secondary_muscles"`
	Contraindications    json.RawMessage `json:"contraindications"`
	EquipmentJson        json.RawMessage `json:"equipment_json"`
	Difficulty           string          `json:"difficulty"`
	Description          string          `json:"description"`
}

func (q *Queries) UpsertExercise(ctx context.Context, arg UpsertExerciseParams) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, upsertExercise,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.PrimaryMuscleGroup,
		arg.SecondaryMusclesJson,
		arg.MovementPattern,
		arg.PrimaryMuscles,
		arg.SecondaryMuscles,
		arg.Contraindications,
		arg.EquipmentJson,
		arg.Difficulty,
		arg.Description,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.PrimaryMuscleGroup,
		&i.SecondaryMusclesJson,
		&i.MovementPattern,
		&i.MovementPatternTaxonomy,
		&i.PrimaryMuscles,
		&i.SecondaryMuscles,
		&i.Contraindications,
		&i.ContraindicationTags,
		&i.EquipmentJson,
		&i.EquipmentRequirements,
		&i.Difficulty,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
