// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: foods.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createFoodLog = `-- name: CreateFoodLog :one
INSERT INTO food_logs (
    user_id,
    datetime,
    food_id,
    quantity,
    unit,
    nutrients_snapshot_json
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, user_id, datetime, food_id, quantity, unit, nutrients_snapshot_json, created_at
`

type CreateFoodLogParams struct {
	UserID                uuid.UUID       `json:"user_id"`
	Datetime              time.Time       `json:"datetime"`
	FoodID                uuid.UUID       `json:"food_id"`
	Quantity              float64         `json:"quantity"`
	Unit                  string          `json:"unit"`
	NutrientsSnapshotJson json.RawMessage `json:"nutrients_snapshot_json"`
}

func (q *Queries) CreateFoodLog(ctx context.Context, arg CreateFoodLogParams) (FoodLog, error) {
	row := q.db.QueryRowContext(ctx, createFoodLog,
		arg.UserID,
		arg.Datetime,
		arg.FoodID,
		arg.Quantity,
		arg.Unit,
		arg.NutrientsSnapshotJson,
	)
	var i FoodLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Datetime,
		&i.FoodID,
		&i.Quantity,
		&i.Unit,
		&i.NutrientsSnapshotJson,
		&i.CreatedAt,
	)
	return i, err
}

const getFoodByID = `-- name: GetFoodByID :one
SELECT id, external_id, provider, label, brand, nutrients_json, created_at, updated_at
FROM foods
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetFoodByID(ctx context.Context, id uuid.UUID) (Food, error) {
	row := q.db.QueryRowContext(ctx, getFoodByID, id)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Provider,
		&i.Label,
		&i.Brand,
		&i.NutrientsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFoodLogDailyTotalsByUserIDAndDate = `-- name: GetFoodLogDailyTotalsByUserIDAndDate :one
SELECT
    COALESCE(SUM(COALESCE(NULLIF(fl.nutrients_snapshot_json->>'calories_kcal', '')::double precision, 0.0)), 0.0)::double precision AS calories_kcal,
    COALESCE(SUM(COALESCE(NULLIF(fl.nutrients_snapshot_json->>'protein_g', '')::double precision, 0.0)), 0.0)::double precision AS protein_g,
    COALESCE(SUM(COALESCE(NULLIF(fl.nutrients_snapshot_json->>'carbs_g', '')::double precision, 0.0)), 0.0)::double precision AS carbs_g,
    COALESCE(SUM(COALESCE(NULLIF(fl.nutrients_snapshot_json->>'fat_g', '')::double precision, 0.0)), 0.0)::double precision AS fat_g
FROM food_logs fl
WHERE fl.user_id = $1
  AND (fl.datetime AT TIME ZONE 'UTC')::date = $2
`

type GetFoodLogDailyTotalsByUserIDAndDateParams struct {
	UserID uuid.UUID `json:"user_id"`
	Date   time.Time `json:"date"`
}

type GetFoodLogDailyTotalsByUserIDAndDateRow struct {
	CaloriesKcal float64 `json:"calories_kcal"`
	ProteinG     float64 `json:"protein_g"`
	CarbsG       float64 `json:"carbs_g"`
	FatG         float64 `json:"fat_g"`
}

func (q *Queries) GetFoodLogDailyTotalsByUserIDAndDate(ctx context.Context, arg GetFoodLogDailyTotalsByUserIDAndDateParams) (GetFoodLogDailyTotalsByUserIDAndDateRow, error) {
	row := q.db.QueryRowContext(ctx, getFoodLogDailyTotalsByUserIDAndDate, arg.UserID, arg.Date)
	var i GetFoodLogDailyTotalsByUserIDAndDateRow
	err := row.Scan(
		&i.CaloriesKcal,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
	)
	return i, err
}

const listFoodLogsByUserIDAndDate = `-- name: ListFoodLogsByUserIDAndDate :many
SELECT
    fl.id,
    fl.user_id,
    fl.datetime,
    fl.food_id,
    fl.quantity,
    fl.unit,
    fl.nutrients_snapshot_json,
    fl.created_at,
    f.external_id,
    f.provider,
    f.label,
    f.brand,
    f.nutrients_json,
    f.created_at,
    f.updated_at
FROM food_logs fl
JOIN foods f ON f.id = fl.food_id
WHERE fl.user_id = $1
  AND (fl.datetime AT TIME ZONE 'UTC')::date = $2
ORDER BY fl.datetime DESC, fl.id DESC
`

type ListFoodLogsByUserIDAndDateParams struct {
	UserID uuid.UUID `json:"user_id"`
	Date   time.Time `json:"date"`
}

type ListFoodLogsByUserIDAndDateRow struct {
	ID                    uuid.UUID       `json:"id"`
	UserID                uuid.UUID       `json:"user_id"`
	Datetime              time.Time       `json:"datetime"`
	FoodID                uuid.UUID       `json:"food_id"`
	Quantity              float64         `json:"quantity"`
	Unit                  string          `json:"unit"`
	NutrientsSnapshotJson json.RawMessage `json:"nutrients_snapshot_json"`
	CreatedAt             time.Time       `json:"created_at"`
	ExternalID            string          `json:"external_id"`
	Provider              string          `json:"provider"`
	Label                 string          `json:"label"`
	Brand                 string          `json:"brand"`
	NutrientsJson         json.RawMessage `json:"nutrients_json"`
	CreatedAt_2           time.Time       `json:"created_at_2"`
	UpdatedAt             time.Time       `json:"updated_at"`
}

func (q *Queries) ListFoodLogsByUserIDAndDate(ctx context.Context, arg ListFoodLogsByUserIDAndDateParams) ([]ListFoodLogsByUserIDAndDateRow, error) {
	rows, err := q.db.QueryContext(ctx, listFoodLogsByUserIDAndDate, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFoodLogsByUserIDAndDateRow{}
	for rows.Next() {
		var i ListFoodLogsByUserIDAndDateRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Datetime,
			&i.FoodID,
			&i.Quantity,
			&i.Unit,
			&i.NutrientsSnapshotJson,
			&i.CreatedAt,
			&i.ExternalID,
			&i.Provider,
			&i.Label,
			&i.Brand,
			&i.NutrientsJson,
			&i.CreatedAt_2,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFood = `-- name: UpsertFood :one
INSERT INTO foods (
    external_id,
    provider,
    label,
    brand,
    nutrients_json
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (provider, external_id)
DO UPDATE SET
    label = EXCLUDED.label,
    brand = EXCLUDED.brand,
    nutrients_json = EXCLUDED.nutrients_json,
    updated_at = NOW()
RETURNING id, external_id, provider, label, brand, nutrients_json, created_at, updated_at
`

type UpsertFoodParams struct {
	ExternalID    string          `json:"external_id"`
	Provider      string          `json:"provider"`
	Label         string          `json:"label"`
	Brand         string          `json:"brand"`
	NutrientsJson json.RawMessage `json:"nutrients_json"`
}

func (q *Queries) UpsertFood(ctx context.Context, arg UpsertFoodParams) (Food, error) {
	row := q.db.QueryRowContext(ctx, upsertFood,
		arg.ExternalID,
		arg.Provider,
		arg.Label,
		arg.Brand,
		arg.NutrientsJson,
	)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Provider,
		&i.Label,
		&i.Brand,
		&i.NutrientsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
