// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: form_check_uploads.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createFormCheckUpload = `-- name: CreateFormCheckUpload :one
INSERT INTO form_check_uploads (
    user_id,
    movement_type,
    recording_started_at,
    recording_ended_at,
    summary_json,
    metadata_json,
    storage_key,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    NOW()
)
RETURNING
    id,
    user_id,
    movement_type,
    recording_started_at,
    recording_ended_at,
    summary_json,
    metadata_json,
    storage_key,
    created_at
`

type CreateFormCheckUploadParams struct {
	UserID             uuid.UUID       `json:"user_id"`
	MovementType       string          `json:"movement_type"`
	RecordingStartedAt time.Time       `json:"recording_started_at"`
	RecordingEndedAt   time.Time       `json:"recording_ended_at"`
	SummaryJson        json.RawMessage `json:"summary_json"`
	MetadataJson       json.RawMessage `json:"metadata_json"`
	StorageKey         string          `json:"storage_key"`
}

func (q *Queries) CreateFormCheckUpload(ctx context.Context, arg CreateFormCheckUploadParams) (FormCheckUpload, error) {
	row := q.db.QueryRowContext(ctx, createFormCheckUpload,
		arg.UserID,
		arg.MovementType,
		arg.RecordingStartedAt,
		arg.RecordingEndedAt,
		arg.SummaryJson,
		arg.MetadataJson,
		arg.StorageKey,
	)
	var i FormCheckUpload
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MovementType,
		&i.RecordingStartedAt,
		&i.RecordingEndedAt,
		&i.SummaryJson,
		&i.MetadataJson,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}
