// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: habits.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countActiveHabitsByUserID = `-- name: CountActiveHabitsByUserID :one
SELECT COUNT(*)
FROM habits
WHERE user_id = $1
  AND active = TRUE
`

func (q *Queries) CountActiveHabitsByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveHabitsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHabit = `-- name: CreateHabit :one
INSERT INTO habits (
    user_id,
    name,
    type,
    target_json,
    active
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, user_id, name, type, target_json, active, created_at
`

type CreateHabitParams struct {
	UserID     uuid.UUID       `json:"user_id"`
	Name       string          `json:"name"`
	Type       string          `json:"type"`
	TargetJson json.RawMessage `json:"target_json"`
	Active     bool            `json:"active"`
}

func (q *Queries) CreateHabit(ctx context.Context, arg CreateHabitParams) (Habit, error) {
	row := q.db.QueryRowContext(ctx, createHabit,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.TargetJson,
		arg.Active,
	)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.TargetJson,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const createHabitDailyLog = `-- name: CreateHabitDailyLog :one
INSERT INTO habit_daily_logs (
    habit_id,
    date,
    completed,
    completed_at
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, habit_id, date, completed, completed_at, created_at
`

type CreateHabitDailyLogParams struct {
	HabitID     uuid.UUID    `json:"habit_id"`
	Date        time.Time    `json:"date"`
	Completed   bool         `json:"completed"`
	CompletedAt sql.NullTime `json:"completed_at"`
}

func (q *Queries) CreateHabitDailyLog(ctx context.Context, arg CreateHabitDailyLogParams) (HabitDailyLog, error) {
	row := q.db.QueryRowContext(ctx, createHabitDailyLog,
		arg.HabitID,
		arg.Date,
		arg.Completed,
		arg.CompletedAt,
	)
	var i HabitDailyLog
	err := row.Scan(
		&i.ID,
		&i.HabitID,
		&i.Date,
		&i.Completed,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getHabitByIDAndUserID = `-- name: GetHabitByIDAndUserID :one
SELECT id, user_id, name, type, target_json, active, created_at
FROM habits
WHERE id = $1
  AND user_id = $2
LIMIT 1
`

type GetHabitByIDAndUserIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetHabitByIDAndUserID(ctx context.Context, arg GetHabitByIDAndUserIDParams) (Habit, error) {
	row := q.db.QueryRowContext(ctx, getHabitByIDAndUserID, arg.ID, arg.UserID)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.TargetJson,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getHabitDailyLogByHabitIDAndDate = `-- name: GetHabitDailyLogByHabitIDAndDate :one
SELECT id, habit_id, date, completed, completed_at, created_at
FROM habit_daily_logs
WHERE habit_id = $1
  AND date = $2
LIMIT 1
`

type GetHabitDailyLogByHabitIDAndDateParams struct {
	HabitID uuid.UUID `json:"habit_id"`
	Date    time.Time `json:"date"`
}

func (q *Queries) GetHabitDailyLogByHabitIDAndDate(ctx context.Context, arg GetHabitDailyLogByHabitIDAndDateParams) (HabitDailyLog, error) {
	row := q.db.QueryRowContext(ctx, getHabitDailyLogByHabitIDAndDate, arg.HabitID, arg.Date)
	var i HabitDailyLog
	err := row.Scan(
		&i.ID,
		&i.HabitID,
		&i.Date,
		&i.Completed,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listHabitDailyLogsByUserID = `-- name: ListHabitDailyLogsByUserID :many
SELECT
    hdl.id,
    hdl.habit_id,
    hdl.date,
    hdl.completed,
    hdl.completed_at,
    hdl.created_at
FROM habit_daily_logs hdl
JOIN habits h ON h.id = hdl.habit_id
WHERE h.user_id = $1
ORDER BY hdl.habit_id ASC, hdl.date ASC
`

func (q *Queries) ListHabitDailyLogsByUserID(ctx context.Context, userID uuid.UUID) ([]HabitDailyLog, error) {
	rows, err := q.db.QueryContext(ctx, listHabitDailyLogsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HabitDailyLog{}
	for rows.Next() {
		var i HabitDailyLog
		if err := rows.Scan(
			&i.ID,
			&i.HabitID,
			&i.Date,
			&i.Completed,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHabitsByUserID = `-- name: ListHabitsByUserID :many
SELECT id, user_id, name, type, target_json, active, created_at
FROM habits
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListHabitsByUserID(ctx context.Context, userID uuid.UUID) ([]Habit, error) {
	rows, err := q.db.QueryContext(ctx, listHabitsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Habit{}
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.TargetJson,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHabitDailyLogCompletion = `-- name: UpdateHabitDailyLogCompletion :one
UPDATE habit_daily_logs
SET completed = $2,
    completed_at = $3
WHERE id = $1
RETURNING id, habit_id, date, completed, completed_at, created_at
`

type UpdateHabitDailyLogCompletionParams struct {
	ID          uuid.UUID    `json:"id"`
	Completed   bool         `json:"completed"`
	CompletedAt sql.NullTime `json:"completed_at"`
}

func (q *Queries) UpdateHabitDailyLogCompletion(ctx context.Context, arg UpdateHabitDailyLogCompletionParams) (HabitDailyLog, error) {
	row := q.db.QueryRowContext(ctx, updateHabitDailyLogCompletion, arg.ID, arg.Completed, arg.CompletedAt)
	var i HabitDailyLog
	err := row.Scan(
		&i.ID,
		&i.HabitID,
		&i.Date,
		&i.Completed,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}
