// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: meal_plans.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createGroceryItem = `-- name: CreateGroceryItem :one
INSERT INTO grocery_items (
    meal_plan_id,
    name,
    quantity,
    unit,
    category
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, meal_plan_id, name, quantity, unit, category, created_at
`

type CreateGroceryItemParams struct {
	MealPlanID uuid.UUID `json:"meal_plan_id"`
	Name       string    `json:"name"`
	Quantity   float64   `json:"quantity"`
	Unit       string    `json:"unit"`
	Category   string    `json:"category"`
}

func (q *Queries) CreateGroceryItem(ctx context.Context, arg CreateGroceryItemParams) (GroceryItem, error) {
	row := q.db.QueryRowContext(ctx, createGroceryItem,
		arg.MealPlanID,
		arg.Name,
		arg.Quantity,
		arg.Unit,
		arg.Category,
	)
	var i GroceryItem
	err := row.Scan(
		&i.ID,
		&i.MealPlanID,
		&i.Name,
		&i.Quantity,
		&i.Unit,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const createMealPlanItem = `-- name: CreateMealPlanItem :one
INSERT INTO meal_plan_items (
    meal_plan_id,
    day_of_week,
    meal_slot,
    recipe_id,
    servings
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, meal_plan_id, day_of_week, meal_slot, recipe_id, servings, created_at
`

type CreateMealPlanItemParams struct {
	MealPlanID uuid.UUID `json:"meal_plan_id"`
	DayOfWeek  int32     `json:"day_of_week"`
	MealSlot   string    `json:"meal_slot"`
	RecipeID   uuid.UUID `json:"recipe_id"`
	Servings   float64   `json:"servings"`
}

func (q *Queries) CreateMealPlanItem(ctx context.Context, arg CreateMealPlanItemParams) (MealPlanItem, error) {
	row := q.db.QueryRowContext(ctx, createMealPlanItem,
		arg.MealPlanID,
		arg.DayOfWeek,
		arg.MealSlot,
		arg.RecipeID,
		arg.Servings,
	)
	var i MealPlanItem
	err := row.Scan(
		&i.ID,
		&i.MealPlanID,
		&i.DayOfWeek,
		&i.MealSlot,
		&i.RecipeID,
		&i.Servings,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGroceryItemsByMealPlanID = `-- name: DeleteGroceryItemsByMealPlanID :exec
DELETE FROM grocery_items
WHERE meal_plan_id = $1
`

func (q *Queries) DeleteGroceryItemsByMealPlanID(ctx context.Context, mealPlanID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGroceryItemsByMealPlanID, mealPlanID)
	return err
}

const deleteMealPlanItemsByMealPlanID = `-- name: DeleteMealPlanItemsByMealPlanID :exec
DELETE FROM meal_plan_items
WHERE meal_plan_id = $1
`

func (q *Queries) DeleteMealPlanItemsByMealPlanID(ctx context.Context, mealPlanID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMealPlanItemsByMealPlanID, mealPlanID)
	return err
}

const getLatestMealPlanByUserID = `-- name: GetLatestMealPlanByUserID :one
SELECT id, user_id, week_start, target_json, created_at, updated_at
FROM meal_plans
WHERE user_id = $1
ORDER BY week_start DESC, updated_at DESC
LIMIT 1
`

func (q *Queries) GetLatestMealPlanByUserID(ctx context.Context, userID uuid.UUID) (MealPlan, error) {
	row := q.db.QueryRowContext(ctx, getLatestMealPlanByUserID, userID)
	var i MealPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeekStart,
		&i.TargetJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMealPlanByUserIDAndWeekStart = `-- name: GetMealPlanByUserIDAndWeekStart :one
SELECT id, user_id, week_start, target_json, created_at, updated_at
FROM meal_plans
WHERE user_id = $1
  AND week_start = $2
LIMIT 1
`

type GetMealPlanByUserIDAndWeekStartParams struct {
	UserID    uuid.UUID `json:"user_id"`
	WeekStart time.Time `json:"week_start"`
}

func (q *Queries) GetMealPlanByUserIDAndWeekStart(ctx context.Context, arg GetMealPlanByUserIDAndWeekStartParams) (MealPlan, error) {
	row := q.db.QueryRowContext(ctx, getMealPlanByUserIDAndWeekStart, arg.UserID, arg.WeekStart)
	var i MealPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeekStart,
		&i.TargetJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGroceryItemsByMealPlanID = `-- name: ListGroceryItemsByMealPlanID :many
SELECT id, meal_plan_id, name, quantity, unit, category, created_at
FROM grocery_items
WHERE meal_plan_id = $1
ORDER BY category ASC, name ASC
`

func (q *Queries) ListGroceryItemsByMealPlanID(ctx context.Context, mealPlanID uuid.UUID) ([]GroceryItem, error) {
	rows, err := q.db.QueryContext(ctx, listGroceryItemsByMealPlanID, mealPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroceryItem{}
	for rows.Next() {
		var i GroceryItem
		if err := rows.Scan(
			&i.ID,
			&i.MealPlanID,
			&i.Name,
			&i.Quantity,
			&i.Unit,
			&i.Category,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealPlanItemsByMealPlanID = `-- name: ListMealPlanItemsByMealPlanID :many
SELECT
    mpi.id,
    mpi.meal_plan_id,
    mpi.day_of_week,
    mpi.meal_slot,
    mpi.recipe_id,
    mpi.servings,
    mpi.created_at,
    r.slug AS recipe_slug,
    r.name AS recipe_name,
    r.meal_type AS recipe_meal_type,
    r.description AS recipe_description,
    r.servings AS recipe_servings,
    r.calories_kcal AS recipe_calories_kcal,
    r.protein_g AS recipe_protein_g,
    r.carbs_g AS recipe_carbs_g,
    r.fat_g AS recipe_fat_g,
    r.ingredients_json AS recipe_ingredients_json,
    r.instructions_json AS recipe_instructions_json
FROM meal_plan_items mpi
JOIN recipes r ON r.id = mpi.recipe_id
WHERE mpi.meal_plan_id = $1
ORDER BY mpi.day_of_week ASC, mpi.meal_slot ASC, mpi.created_at ASC
`

type ListMealPlanItemsByMealPlanIDRow struct {
	ID                     uuid.UUID       `json:"id"`
	MealPlanID             uuid.UUID       `json:"meal_plan_id"`
	DayOfWeek              int32           `json:"day_of_week"`
	MealSlot               string          `json:"meal_slot"`
	RecipeID               uuid.UUID       `json:"recipe_id"`
	Servings               float64         `json:"servings"`
	CreatedAt              time.Time       `json:"created_at"`
	RecipeSlug             string          `json:"recipe_slug"`
	RecipeName             string          `json:"recipe_name"`
	RecipeMealType         string          `json:"recipe_meal_type"`
	RecipeDescription      string          `json:"recipe_description"`
	RecipeServings         float64         `json:"recipe_servings"`
	RecipeCaloriesKcal     int32           `json:"recipe_calories_kcal"`
	RecipeProteinG         int32           `json:"recipe_protein_g"`
	RecipeCarbsG           int32           `json:"recipe_carbs_g"`
	RecipeFatG             int32           `json:"recipe_fat_g"`
	RecipeIngredientsJson  json.RawMessage `json:"recipe_ingredients_json"`
	RecipeInstructionsJson json.RawMessage `json:"recipe_instructions_json"`
}

func (q *Queries) ListMealPlanItemsByMealPlanID(ctx context.Context, mealPlanID uuid.UUID) ([]ListMealPlanItemsByMealPlanIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listMealPlanItemsByMealPlanID, mealPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMealPlanItemsByMealPlanIDRow{}
	for rows.Next() {
		var i ListMealPlanItemsByMealPlanIDRow
		if err := rows.Scan(
			&i.ID,
			&i.MealPlanID,
			&i.DayOfWeek,
			&i.MealSlot,
			&i.RecipeID,
			&i.Servings,
			&i.CreatedAt,
			&i.RecipeSlug,
			&i.RecipeName,
			&i.RecipeMealType,
			&i.RecipeDescription,
			&i.RecipeServings,
			&i.RecipeCaloriesKcal,
			&i.RecipeProteinG,
			&i.RecipeCarbsG,
			&i.RecipeFatG,
			&i.RecipeIngredientsJson,
			&i.RecipeInstructionsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipes = `-- name: ListRecipes :many
SELECT
    id,
    slug,
    name,
    meal_type,
    description,
    servings,
    calories_kcal,
    protein_g,
    carbs_g,
    fat_g,
    ingredients_json,
    instructions_json,
    created_at,
    updated_at
FROM recipes
ORDER BY meal_type ASC, name ASC
`

func (q *Queries) ListRecipes(ctx context.Context) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, listRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipe{}
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.MealType,
			&i.Description,
			&i.Servings,
			&i.CaloriesKcal,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
			&i.IngredientsJson,
			&i.InstructionsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMealPlan = `-- name: UpsertMealPlan :one
INSERT INTO meal_plans (
    user_id,
    week_start,
    target_json
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (user_id, week_start)
DO UPDATE SET
    target_json = EXCLUDED.target_json,
    updated_at = NOW()
RETURNING id, user_id, week_start, target_json, created_at, updated_at
`

type UpsertMealPlanParams struct {
	UserID     uuid.UUID       `json:"user_id"`
	WeekStart  time.Time       `json:"week_start"`
	TargetJson json.RawMessage `json:"target_json"`
}

func (q *Queries) UpsertMealPlan(ctx context.Context, arg UpsertMealPlanParams) (MealPlan, error) {
	row := q.db.QueryRowContext(ctx, upsertMealPlan, arg.UserID, arg.WeekStart, arg.TargetJson)
	var i MealPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeekStart,
		&i.TargetJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
