// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AppEvent struct {
	ID             uuid.UUID       `json:"id"`
	UserID         uuid.NullUUID   `json:"user_id"`
	EventName      string          `json:"event_name"`
	EventTime      time.Time       `json:"event_time"`
	PropertiesJson json.RawMessage `json:"properties_json"`
	CreatedAt      time.Time       `json:"created_at"`
}

type CoachSession struct {
	ID              uuid.UUID `json:"id"`
	CrewID          uuid.UUID `json:"crew_id"`
	Title           string    `json:"title"`
	Description     string    `json:"description"`
	CoachName       string    `json:"coach_name"`
	DurationSeconds int32     `json:"duration_seconds"`
	RequiredTier    string    `json:"required_tier"`
	Published       bool      `json:"published"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type CoachSessionAsset struct {
	ID             uuid.UUID `json:"id"`
	CoachSessionID uuid.UUID `json:"coach_session_id"`
	AssetType      string    `json:"asset_type"`
	StorageKey     string    `json:"storage_key"`
	MimeType       string    `json:"mime_type"`
	CreatedAt      time.Time `json:"created_at"`
}

type Consent struct {
	ID           uuid.UUID       `json:"id"`
	UserID       uuid.UUID       `json:"user_id"`
	ConsentType  string          `json:"consent_type"`
	GrantedAt    time.Time       `json:"granted_at"`
	RevokedAt    sql.NullTime    `json:"revoked_at"`
	MetadataJson json.RawMessage `json:"metadata_json"`
}

type Crew struct {
	ID              uuid.UUID      `json:"id"`
	Name            string         `json:"name"`
	Description     string         `json:"description"`
	CreatedByUserID uuid.UUID      `json:"created_by_user_id"`
	IsPrivate       bool           `json:"is_private"`
	SharedPlanUrl   sql.NullString `json:"shared_plan_url"`
	SharedHabitsUrl sql.NullString `json:"shared_habits_url"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type CrewInvite struct {
	ID              uuid.UUID    `json:"id"`
	CrewID          uuid.UUID    `json:"crew_id"`
	InviteCode      string       `json:"invite_code"`
	InvitedByUserID uuid.UUID    `json:"invited_by_user_id"`
	MaxUses         int32        `json:"max_uses"`
	UsesCount       int32        `json:"uses_count"`
	ExpiresAt       sql.NullTime `json:"expires_at"`
	RevokedAt       sql.NullTime `json:"revoked_at"`
	CreatedAt       time.Time    `json:"created_at"`
}

type CrewMember struct {
	CrewID   uuid.UUID `json:"crew_id"`
	UserID   uuid.UUID `json:"user_id"`
	Role     string    `json:"role"`
	JoinedAt time.Time `json:"joined_at"`
}

type CueTimeline struct {
	ID                         uuid.UUID     `json:"id"`
	CoachSessionID             uuid.UUID     `json:"coach_session_id"`
	CueIndex                   int32         `json:"cue_index"`
	StartMs                    int32         `json:"start_ms"`
	EndMs                      int32         `json:"end_ms"`
	CueText                    string        `json:"cue_text"`
	BiomechanicsExerciseID     uuid.NullUUID `json:"biomechanics_exercise_id"`
	BiomechanicsDefinitionType string        `json:"biomechanics_definition_type"`
	BiomechanicsDefinitionKey  string        `json:"biomechanics_definition_key"`
	CreatedAt                  time.Time     `json:"created_at"`
}

type Exercise struct {
	ID                      uuid.UUID       `json:"id"`
	Slug                    string          `json:"slug"`
	Name                    string          `json:"name"`
	PrimaryMuscleGroup      string          `json:"primary_muscle_group"`
	SecondaryMusclesJson    json.RawMessage `json:"secondary_muscles_json"`
	MovementPattern         string          `json:"movement_pattern"`
	MovementPatternTaxonomy json.RawMessage `json:"movement_pattern_taxonomy"`
	PrimaryMuscles          json.RawMessage `json:"primary_muscles"`
	SecondaryMuscles        json.RawMessage `json:"secondary_muscles"`
	Contraindications       json.RawMessage `json:"contraindications"`
	ContraindicationTags    json.RawMessage `json:"contraindication_tags"`
	EquipmentJson           json.RawMessage `json:"equipment_json"`
	EquipmentRequirements   json.RawMessage `json:"equipment_requirements"`
	Difficulty              string          `json:"difficulty"`
	Description             string          `json:"description"`
	CreatedAt               time.Time       `json:"created_at"`
}

type ExerciseBiomechAsset struct {
	ID                uuid.UUID       `json:"id"`
	ExerciseID        uuid.UUID       `json:"exercise_id"`
	AnimationAssetKey string          `json:"animation_asset_key"`
	RigVersion        string          `json:"rig_version"`
	MetadataJson      json.RawMessage `json:"metadata_json"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type ExerciseBiomechAssetMuscleGroup struct {
	BiomechAssetID  uuid.UUID `json:"biomech_asset_id"`
	MuscleGroupSlug string    `json:"muscle_group_slug"`
	ActivationLevel float64   `json:"activation_level"`
	Role            string    `json:"role"`
}

type ExerciseMedium struct {
	ID              uuid.UUID      `json:"id"`
	ExerciseID      uuid.UUID      `json:"exercise_id"`
	MediaType       string         `json:"media_type"`
	Uri             string         `json:"uri"`
	ThumbnailUri    sql.NullString `json:"thumbnail_uri"`
	DurationSeconds sql.NullInt32  `json:"duration_seconds"`
	CreatedAt       time.Time      `json:"created_at"`
}

type Food struct {
	ID            uuid.UUID       `json:"id"`
	ExternalID    string          `json:"external_id"`
	Provider      string          `json:"provider"`
	Label         string          `json:"label"`
	Brand         string          `json:"brand"`
	NutrientsJson json.RawMessage `json:"nutrients_json"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type FoodLog struct {
	ID                    uuid.UUID       `json:"id"`
	UserID                uuid.UUID       `json:"user_id"`
	Datetime              time.Time       `json:"datetime"`
	FoodID                uuid.UUID       `json:"food_id"`
	Quantity              float64         `json:"quantity"`
	Unit                  string          `json:"unit"`
	NutrientsSnapshotJson json.RawMessage `json:"nutrients_snapshot_json"`
	CreatedAt             time.Time       `json:"created_at"`
}

type FormCheckUpload struct {
	ID                 uuid.UUID       `json:"id"`
	UserID             uuid.UUID       `json:"user_id"`
	MovementType       string          `json:"movement_type"`
	RecordingStartedAt time.Time       `json:"recording_started_at"`
	RecordingEndedAt   time.Time       `json:"recording_ended_at"`
	SummaryJson        json.RawMessage `json:"summary_json"`
	MetadataJson       json.RawMessage `json:"metadata_json"`
	StorageKey         string          `json:"storage_key"`
	CreatedAt          time.Time       `json:"created_at"`
}

type GroceryItem struct {
	ID         uuid.UUID `json:"id"`
	MealPlanID uuid.UUID `json:"meal_plan_id"`
	Name       string    `json:"name"`
	Quantity   float64   `json:"quantity"`
	Unit       string    `json:"unit"`
	Category   string    `json:"category"`
	CreatedAt  time.Time `json:"created_at"`
}

type Habit struct {
	ID         uuid.UUID       `json:"id"`
	UserID     uuid.UUID       `json:"user_id"`
	Name       string          `json:"name"`
	Type       string          `json:"type"`
	TargetJson json.RawMessage `json:"target_json"`
	Active     bool            `json:"active"`
	CreatedAt  time.Time       `json:"created_at"`
}

type HabitDailyLog struct {
	ID          uuid.UUID    `json:"id"`
	HabitID     uuid.UUID    `json:"habit_id"`
	Date        time.Time    `json:"date"`
	Completed   bool         `json:"completed"`
	CompletedAt sql.NullTime `json:"completed_at"`
	CreatedAt   time.Time    `json:"created_at"`
}

type MealPlan struct {
	ID         uuid.UUID       `json:"id"`
	UserID     uuid.UUID       `json:"user_id"`
	WeekStart  time.Time       `json:"week_start"`
	TargetJson json.RawMessage `json:"target_json"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

type MealPlanItem struct {
	ID         uuid.UUID `json:"id"`
	MealPlanID uuid.UUID `json:"meal_plan_id"`
	DayOfWeek  int32     `json:"day_of_week"`
	MealSlot   string    `json:"meal_slot"`
	RecipeID   uuid.UUID `json:"recipe_id"`
	Servings   float64   `json:"servings"`
	CreatedAt  time.Time `json:"created_at"`
}

type MomentumSprintDailyChecklistEntry struct {
	ID           uuid.UUID    `json:"id"`
	EnrollmentID uuid.UUID    `json:"enrollment_id"`
	Date         time.Time    `json:"date"`
	HabitKey     string       `json:"habit_key"`
	HabitLabel   string       `json:"habit_label"`
	DisplayOrder int32        `json:"display_order"`
	Completed    bool         `json:"completed"`
	CompletedAt  sql.NullTime `json:"completed_at"`
	CreatedAt    time.Time    `json:"created_at"`
}

type MomentumSprintEnrollment struct {
	ID          uuid.UUID    `json:"id"`
	UserID      uuid.UUID    `json:"user_id"`
	Goal        string       `json:"goal"`
	StartDate   time.Time    `json:"start_date"`
	EndDate     time.Time    `json:"end_date"`
	CompletedAt sql.NullTime `json:"completed_at"`
	CreatedAt   time.Time    `json:"created_at"`
}

type MomentumSprintRewardMilestone struct {
	ID           uuid.UUID    `json:"id"`
	EnrollmentID uuid.UUID    `json:"enrollment_id"`
	MilestoneDay int32        `json:"milestone_day"`
	RewardLabel  string       `json:"reward_label"`
	UnlockedAt   sql.NullTime `json:"unlocked_at"`
	CreatedAt    time.Time    `json:"created_at"`
}

type MuscleGroup struct {
	Slug        string    `json:"slug"`
	DisplayName string    `json:"display_name"`
	Region      string    `json:"region"`
	CreatedAt   time.Time `json:"created_at"`
}

type NutritionDailyCheckin struct {
	ID               uuid.UUID     `json:"id"`
	UserID           uuid.UUID     `json:"user_id"`
	Date             time.Time     `json:"date"`
	CaloriesEstimate sql.NullInt32 `json:"calories_estimate"`
	ProteinGEstimate sql.NullInt32 `json:"protein_g_estimate"`
	HitCalories      bool          `json:"hit_calories"`
	HitProtein       bool          `json:"hit_protein"`
	Notes            string        `json:"notes"`
	CreatedAt        time.Time     `json:"created_at"`
}

type NutritionTarget struct {
	UserID         uuid.UUID `json:"user_id"`
	CaloriesTarget int32     `json:"calories_target"`
	ProteinGTarget int32     `json:"protein_g_target"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Program struct {
	ID           uuid.UUID       `json:"id"`
	Slug         string          `json:"slug"`
	Name         string          `json:"name"`
	Description  string          `json:"description"`
	GoalTagsJson json.RawMessage `json:"goal_tags_json"`
	Level        string          `json:"level"`
	WeeksLength  int32           `json:"weeks_length"`
	CreatedAt    time.Time       `json:"created_at"`
}

type ProgramSession struct {
	ID            uuid.UUID `json:"id"`
	ProgramWeekID uuid.UUID `json:"program_week_id"`
	DayOfWeek     int32     `json:"day_of_week"`
	Name          string    `json:"name"`
	CreatedAt     time.Time `json:"created_at"`
}

type ProgramSessionExercise struct {
	ID               uuid.UUID       `json:"id"`
	ProgramSessionID uuid.UUID       `json:"program_session_id"`
	ExerciseID       uuid.UUID       `json:"exercise_id"`
	PrescriptionJson json.RawMessage `json:"prescription_json"`
	OrderIndex       int32           `json:"order_index"`
}

type ProgramWeek struct {
	ID        uuid.UUID `json:"id"`
	ProgramID uuid.UUID `json:"program_id"`
	WeekIndex int32     `json:"week_index"`
	CreatedAt time.Time `json:"created_at"`
}

type ReadinessCheckin struct {
	UserID         uuid.UUID `json:"user_id"`
	Date           time.Time `json:"date"`
	EnergyLevel    int32     `json:"energy_level"`
	SleepQuality   int32     `json:"sleep_quality"`
	StressLevel    int32     `json:"stress_level"`
	ReadinessScore float64   `json:"readiness_score"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Recipe struct {
	ID               uuid.UUID       `json:"id"`
	Slug             string          `json:"slug"`
	Name             string          `json:"name"`
	MealType         string          `json:"meal_type"`
	Description      string          `json:"description"`
	Servings         float64         `json:"servings"`
	CaloriesKcal     int32           `json:"calories_kcal"`
	ProteinG         int32           `json:"protein_g"`
	CarbsG           int32           `json:"carbs_g"`
	FatG             int32           `json:"fat_g"`
	IngredientsJson  json.RawMessage `json:"ingredients_json"`
	InstructionsJson json.RawMessage `json:"instructions_json"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}

type Session struct {
	ID               uuid.UUID    `json:"id"`
	UserID           uuid.UUID    `json:"user_id"`
	RefreshTokenHash string       `json:"refresh_token_hash"`
	ExpiresAt        time.Time    `json:"expires_at"`
	CreatedAt        time.Time    `json:"created_at"`
	RevokedAt        sql.NullTime `json:"revoked_at"`
}

type Subscription struct {
	ID                    uuid.UUID       `json:"id"`
	UserID                uuid.UUID       `json:"user_id"`
	Platform              string          `json:"platform"`
	ProductID             string          `json:"product_id"`
	Status                string          `json:"status"`
	ExpiresAt             sql.NullTime    `json:"expires_at"`
	RawReceipt            json.RawMessage `json:"raw_receipt"`
	TransactionID         string          `json:"transaction_id"`
	OriginalTransactionID sql.NullString  `json:"original_transaction_id"`
	CreatedAt             time.Time       `json:"created_at"`
	UpdatedAt             time.Time       `json:"updated_at"`
}

type SubscriptionProductEntitlement struct {
	ProductID   string `json:"product_id"`
	Entitlement string `json:"entitlement"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

type UserEntitlement struct {
	UserID      uuid.UUID   `json:"user_id"`
	Entitlement string      `json:"entitlement"`
	ExpiresAt   interface{} `json:"expires_at"`
}

type UserExerciseProgress struct {
	UserID     uuid.UUID       `json:"user_id"`
	ExerciseID uuid.UUID       `json:"exercise_id"`
	LastLoad   float64         `json:"last_load"`
	LastReps   int32           `json:"last_reps"`
	LastRpe    sql.NullFloat64 `json:"last_rpe"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

type UserGoal struct {
	UserID                   uuid.UUID             `json:"user_id"`
	PrimaryGoal              string                `json:"primary_goal"`
	SecondaryGoal            sql.NullString        `json:"secondary_goal"`
	DaysPerWeek              int32                 `json:"days_per_week"`
	SessionDurationMinutes   int32                 `json:"session_duration_minutes"`
	EquipmentAccessJson      json.RawMessage       `json:"equipment_access_json"`
	ConstraintsJson          json.RawMessage       `json:"constraints_json"`
	InjuriesLimitationsJson  json.RawMessage       `json:"injuries_limitations_json"`
	ModalityPreferencesJson  json.RawMessage       `json:"modality_preferences_json"`
	PriorTrainingHistoryJson pqtype.NullRawMessage `json:"prior_training_history_json"`
	ReadinessSignalsJson     pqtype.NullRawMessage `json:"readiness_signals_json"`
	CreatedAt                time.Time             `json:"created_at"`
	UpdatedAt                time.Time             `json:"updated_at"`
}

type UserProfile struct {
	UserID          uuid.UUID `json:"user_id"`
	DisplayName     string    `json:"display_name"`
	Sex             string    `json:"sex"`
	HeightCm        int32     `json:"height_cm"`
	WeightKg        float64   `json:"weight_kg"`
	ExperienceLevel string    `json:"experience_level"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type UserProgramEnrollment struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	ProgramID   uuid.UUID `json:"program_id"`
	StartDate   time.Time `json:"start_date"`
	CurrentWeek int32     `json:"current_week"`
	CreatedAt   time.Time `json:"created_at"`
}

type UserProgramState struct {
	UserID                       uuid.UUID       `json:"user_id"`
	ProgramID                    uuid.UUID       `json:"program_id"`
	CurrentWeek                  int32           `json:"current_week"`
	DeloadFlag                   bool            `json:"deload_flag"`
	LastWeekAdherence            float64         `json:"last_week_adherence"`
	LastWeekScheduledSessions    int32           `json:"last_week_scheduled_sessions"`
	LastWeekCompletedSessions    int32           `json:"last_week_completed_sessions"`
	LastWeekDensity              float64         `json:"last_week_density"`
	LastWeekHighRpeRate          float64         `json:"last_week_high_rpe_rate"`
	FatigueScore                 float64         `json:"fatigue_score"`
	ConsecutiveLowAdherenceWeeks int32           `json:"consecutive_low_adherence_weeks"`
	AdjustmentReasonsJson        json.RawMessage `json:"adjustment_reasons_json"`
	UpdatedAt                    time.Time       `json:"updated_at"`
}

type UserWeightEntry struct {
	UserID    uuid.UUID `json:"user_id"`
	Date      time.Time `json:"date"`
	WeightKg  float64   `json:"weight_kg"`
	Unit      string    `json:"unit"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type WeeklyCheckin struct {
	UserID         uuid.UUID       `json:"user_id"`
	WeekStart      time.Time       `json:"week_start"`
	Adherence      float64         `json:"adherence"`
	WeightChange   float64         `json:"weight_change"`
	NewTargetsJson json.RawMessage `json:"new_targets_json"`
	Explanation    string          `json:"explanation"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type Workout struct {
	ID               uuid.UUID     `json:"id"`
	UserID           uuid.UUID     `json:"user_id"`
	ProgramSessionID uuid.NullUUID `json:"program_session_id"`
	StartedAt        time.Time     `json:"started_at"`
	CompletedAt      sql.NullTime  `json:"completed_at"`
	Notes            string        `json:"notes"`
	CreatedAt        time.Time     `json:"created_at"`
}

type WorkoutExercise struct {
	ID          uuid.UUID       `json:"id"`
	WorkoutID   uuid.UUID       `json:"workout_id"`
	ExerciseID  uuid.UUID       `json:"exercise_id"`
	OrderIndex  int32           `json:"order_index"`
	PlannedJson json.RawMessage `json:"planned_json"`
	ActualJson  json.RawMessage `json:"actual_json"`
	CreatedAt   time.Time       `json:"created_at"`
}

type WorkoutSet struct {
	ID                uuid.UUID       `json:"id"`
	WorkoutExerciseID uuid.UUID       `json:"workout_exercise_id"`
	SetIndex          int32           `json:"set_index"`
	Reps              int32           `json:"reps"`
	WeightKg          float64         `json:"weight_kg"`
	Rpe               sql.NullFloat64 `json:"rpe"`
	CompletedAt       time.Time       `json:"completed_at"`
	CreatedAt         time.Time       `json:"created_at"`
	IdempotencyKey    sql.NullString  `json:"idempotency_key"`
}
