// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: momentum_sprint.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createMomentumSprintChecklistEntry = `-- name: CreateMomentumSprintChecklistEntry :one
INSERT INTO momentum_sprint_daily_checklist_entries (
    enrollment_id,
    date,
    habit_key,
    habit_label,
    display_order,
    completed,
    completed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, enrollment_id, date, habit_key, habit_label, display_order, completed, completed_at, created_at
`

type CreateMomentumSprintChecklistEntryParams struct {
	EnrollmentID uuid.UUID    `json:"enrollment_id"`
	Date         time.Time    `json:"date"`
	HabitKey     string       `json:"habit_key"`
	HabitLabel   string       `json:"habit_label"`
	DisplayOrder int32        `json:"display_order"`
	Completed    bool         `json:"completed"`
	CompletedAt  sql.NullTime `json:"completed_at"`
}

func (q *Queries) CreateMomentumSprintChecklistEntry(ctx context.Context, arg CreateMomentumSprintChecklistEntryParams) (MomentumSprintDailyChecklistEntry, error) {
	row := q.db.QueryRowContext(ctx, createMomentumSprintChecklistEntry,
		arg.EnrollmentID,
		arg.Date,
		arg.HabitKey,
		arg.HabitLabel,
		arg.DisplayOrder,
		arg.Completed,
		arg.CompletedAt,
	)
	var i MomentumSprintDailyChecklistEntry
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.Date,
		&i.HabitKey,
		&i.HabitLabel,
		&i.DisplayOrder,
		&i.Completed,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createMomentumSprintRewardMilestone = `-- name: CreateMomentumSprintRewardMilestone :one
INSERT INTO momentum_sprint_reward_milestones (
    enrollment_id,
    milestone_day,
    reward_label,
    unlocked_at
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, enrollment_id, milestone_day, reward_label, unlocked_at, created_at
`

type CreateMomentumSprintRewardMilestoneParams struct {
	EnrollmentID uuid.UUID    `json:"enrollment_id"`
	MilestoneDay int32        `json:"milestone_day"`
	RewardLabel  string       `json:"reward_label"`
	UnlockedAt   sql.NullTime `json:"unlocked_at"`
}

func (q *Queries) CreateMomentumSprintRewardMilestone(ctx context.Context, arg CreateMomentumSprintRewardMilestoneParams) (MomentumSprintRewardMilestone, error) {
	row := q.db.QueryRowContext(ctx, createMomentumSprintRewardMilestone,
		arg.EnrollmentID,
		arg.MilestoneDay,
		arg.RewardLabel,
		arg.UnlockedAt,
	)
	var i MomentumSprintRewardMilestone
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.MilestoneDay,
		&i.RewardLabel,
		&i.UnlockedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMomentumSprintChecklistEntriesByEnrollmentID = `-- name: DeleteMomentumSprintChecklistEntriesByEnrollmentID :exec
DELETE FROM momentum_sprint_daily_checklist_entries
WHERE enrollment_id = $1
`

func (q *Queries) DeleteMomentumSprintChecklistEntriesByEnrollmentID(ctx context.Context, enrollmentID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMomentumSprintChecklistEntriesByEnrollmentID, enrollmentID)
	return err
}

const deleteMomentumSprintRewardMilestonesByEnrollmentID = `-- name: DeleteMomentumSprintRewardMilestonesByEnrollmentID :exec
DELETE FROM momentum_sprint_reward_milestones
WHERE enrollment_id = $1
`

func (q *Queries) DeleteMomentumSprintRewardMilestonesByEnrollmentID(ctx context.Context, enrollmentID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMomentumSprintRewardMilestonesByEnrollmentID, enrollmentID)
	return err
}

const getMomentumSprintEnrollmentByUserID = `-- name: GetMomentumSprintEnrollmentByUserID :one
SELECT id, user_id, goal, start_date, end_date, completed_at, created_at
FROM momentum_sprint_enrollments
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetMomentumSprintEnrollmentByUserID(ctx context.Context, userID uuid.UUID) (MomentumSprintEnrollment, error) {
	row := q.db.QueryRowContext(ctx, getMomentumSprintEnrollmentByUserID, userID)
	var i MomentumSprintEnrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Goal,
		&i.StartDate,
		&i.EndDate,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listMomentumSprintChecklistEntriesByEnrollmentIDAndDate = `-- name: ListMomentumSprintChecklistEntriesByEnrollmentIDAndDate :many
SELECT id, enrollment_id, date, habit_key, habit_label, display_order, completed, completed_at, created_at
FROM momentum_sprint_daily_checklist_entries
WHERE enrollment_id = $1
  AND date = $2
ORDER BY display_order ASC, habit_key ASC
`

type ListMomentumSprintChecklistEntriesByEnrollmentIDAndDateParams struct {
	EnrollmentID uuid.UUID `json:"enrollment_id"`
	Date         time.Time `json:"date"`
}

func (q *Queries) ListMomentumSprintChecklistEntriesByEnrollmentIDAndDate(ctx context.Context, arg ListMomentumSprintChecklistEntriesByEnrollmentIDAndDateParams) ([]MomentumSprintDailyChecklistEntry, error) {
	rows, err := q.db.QueryContext(ctx, listMomentumSprintChecklistEntriesByEnrollmentIDAndDate, arg.EnrollmentID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MomentumSprintDailyChecklistEntry{}
	for rows.Next() {
		var i MomentumSprintDailyChecklistEntry
		if err := rows.Scan(
			&i.ID,
			&i.EnrollmentID,
			&i.Date,
			&i.HabitKey,
			&i.HabitLabel,
			&i.DisplayOrder,
			&i.Completed,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMomentumSprintDailySummaryByEnrollmentID = `-- name: ListMomentumSprintDailySummaryByEnrollmentID :many
SELECT
    date,
    COUNT(*)::int AS total_entries,
    COUNT(*) FILTER (WHERE completed)::int AS completed_entries
FROM momentum_sprint_daily_checklist_entries
WHERE enrollment_id = $1
GROUP BY date
ORDER BY date ASC
`

type ListMomentumSprintDailySummaryByEnrollmentIDRow struct {
	Date             time.Time `json:"date"`
	TotalEntries     int32     `json:"total_entries"`
	CompletedEntries int32     `json:"completed_entries"`
}

func (q *Queries) ListMomentumSprintDailySummaryByEnrollmentID(ctx context.Context, enrollmentID uuid.UUID) ([]ListMomentumSprintDailySummaryByEnrollmentIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listMomentumSprintDailySummaryByEnrollmentID, enrollmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMomentumSprintDailySummaryByEnrollmentIDRow{}
	for rows.Next() {
		var i ListMomentumSprintDailySummaryByEnrollmentIDRow
		if err := rows.Scan(&i.Date, &i.TotalEntries, &i.CompletedEntries); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMomentumSprintRewardMilestonesByEnrollmentID = `-- name: ListMomentumSprintRewardMilestonesByEnrollmentID :many
SELECT id, enrollment_id, milestone_day, reward_label, unlocked_at, created_at
FROM momentum_sprint_reward_milestones
WHERE enrollment_id = $1
ORDER BY milestone_day ASC
`

func (q *Queries) ListMomentumSprintRewardMilestonesByEnrollmentID(ctx context.Context, enrollmentID uuid.UUID) ([]MomentumSprintRewardMilestone, error) {
	rows, err := q.db.QueryContext(ctx, listMomentumSprintRewardMilestonesByEnrollmentID, enrollmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MomentumSprintRewardMilestone{}
	for rows.Next() {
		var i MomentumSprintRewardMilestone
		if err := rows.Scan(
			&i.ID,
			&i.EnrollmentID,
			&i.MilestoneDay,
			&i.RewardLabel,
			&i.UnlockedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlockMomentumSprintRewardMilestonesByEnrollmentID = `-- name: UnlockMomentumSprintRewardMilestonesByEnrollmentID :exec
UPDATE momentum_sprint_reward_milestones
SET unlocked_at = COALESCE(unlocked_at, $2)
WHERE enrollment_id = $1
  AND milestone_day <= $3
`

type UnlockMomentumSprintRewardMilestonesByEnrollmentIDParams struct {
	EnrollmentID uuid.UUID    `json:"enrollment_id"`
	UnlockedAt   sql.NullTime `json:"unlocked_at"`
	MilestoneDay int32        `json:"milestone_day"`
}

func (q *Queries) UnlockMomentumSprintRewardMilestonesByEnrollmentID(ctx context.Context, arg UnlockMomentumSprintRewardMilestonesByEnrollmentIDParams) error {
	_, err := q.db.ExecContext(ctx, unlockMomentumSprintRewardMilestonesByEnrollmentID, arg.EnrollmentID, arg.UnlockedAt, arg.MilestoneDay)
	return err
}

const updateMomentumSprintChecklistEntryCompletion = `-- name: UpdateMomentumSprintChecklistEntryCompletion :one
UPDATE momentum_sprint_daily_checklist_entries
SET completed = $4,
    completed_at = $5
WHERE enrollment_id = $1
  AND date = $2
  AND habit_key = $3
RETURNING id, enrollment_id, date, habit_key, habit_label, display_order, completed, completed_at, created_at
`

type UpdateMomentumSprintChecklistEntryCompletionParams struct {
	EnrollmentID uuid.UUID    `json:"enrollment_id"`
	Date         time.Time    `json:"date"`
	HabitKey     string       `json:"habit_key"`
	Completed    bool         `json:"completed"`
	CompletedAt  sql.NullTime `json:"completed_at"`
}

func (q *Queries) UpdateMomentumSprintChecklistEntryCompletion(ctx context.Context, arg UpdateMomentumSprintChecklistEntryCompletionParams) (MomentumSprintDailyChecklistEntry, error) {
	row := q.db.QueryRowContext(ctx, updateMomentumSprintChecklistEntryCompletion,
		arg.EnrollmentID,
		arg.Date,
		arg.HabitKey,
		arg.Completed,
		arg.CompletedAt,
	)
	var i MomentumSprintDailyChecklistEntry
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.Date,
		&i.HabitKey,
		&i.HabitLabel,
		&i.DisplayOrder,
		&i.Completed,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateMomentumSprintEnrollmentCompletedAt = `-- name: UpdateMomentumSprintEnrollmentCompletedAt :one
UPDATE momentum_sprint_enrollments
SET completed_at = $2
WHERE id = $1
RETURNING id, user_id, goal, start_date, end_date, completed_at, created_at
`

type UpdateMomentumSprintEnrollmentCompletedAtParams struct {
	ID          uuid.UUID    `json:"id"`
	CompletedAt sql.NullTime `json:"completed_at"`
}

func (q *Queries) UpdateMomentumSprintEnrollmentCompletedAt(ctx context.Context, arg UpdateMomentumSprintEnrollmentCompletedAtParams) (MomentumSprintEnrollment, error) {
	row := q.db.QueryRowContext(ctx, updateMomentumSprintEnrollmentCompletedAt, arg.ID, arg.CompletedAt)
	var i MomentumSprintEnrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Goal,
		&i.StartDate,
		&i.EndDate,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertMomentumSprintEnrollment = `-- name: UpsertMomentumSprintEnrollment :one
INSERT INTO momentum_sprint_enrollments (
    user_id,
    goal,
    start_date,
    end_date,
    completed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    NULL
)
ON CONFLICT (user_id) DO UPDATE
SET goal = EXCLUDED.goal,
    start_date = EXCLUDED.start_date,
    end_date = EXCLUDED.end_date,
    completed_at = NULL,
    created_at = NOW()
RETURNING id, user_id, goal, start_date, end_date, completed_at, created_at
`

type UpsertMomentumSprintEnrollmentParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Goal      string    `json:"goal"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

func (q *Queries) UpsertMomentumSprintEnrollment(ctx context.Context, arg UpsertMomentumSprintEnrollmentParams) (MomentumSprintEnrollment, error) {
	row := q.db.QueryRowContext(ctx, upsertMomentumSprintEnrollment,
		arg.UserID,
		arg.Goal,
		arg.StartDate,
		arg.EndDate,
	)
	var i MomentumSprintEnrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Goal,
		&i.StartDate,
		&i.EndDate,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}
