// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: nutrition.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getLatestUserWeightEntryByDateRange = `-- name: GetLatestUserWeightEntryByDateRange :one
SELECT user_id, date, weight_kg, unit, created_at, updated_at
FROM user_weight_entries
WHERE user_id = $1
  AND date >= $2
  AND date < $3
ORDER BY date DESC, updated_at DESC
LIMIT 1
`

type GetLatestUserWeightEntryByDateRangeParams struct {
	UserID    uuid.UUID `json:"user_id"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

func (q *Queries) GetLatestUserWeightEntryByDateRange(ctx context.Context, arg GetLatestUserWeightEntryByDateRangeParams) (UserWeightEntry, error) {
	row := q.db.QueryRowContext(ctx, getLatestUserWeightEntryByDateRange, arg.UserID, arg.StartDate, arg.EndDate)
	var i UserWeightEntry
	err := row.Scan(
		&i.UserID,
		&i.Date,
		&i.WeightKg,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestWeeklyCheckinByUserID = `-- name: GetLatestWeeklyCheckinByUserID :one
SELECT user_id, week_start, adherence, weight_change, new_targets_json, explanation, created_at, updated_at
FROM weekly_checkins
WHERE user_id = $1
ORDER BY week_start DESC
LIMIT 1
`

func (q *Queries) GetLatestWeeklyCheckinByUserID(ctx context.Context, userID uuid.UUID) (WeeklyCheckin, error) {
	row := q.db.QueryRowContext(ctx, getLatestWeeklyCheckinByUserID, userID)
	var i WeeklyCheckin
	err := row.Scan(
		&i.UserID,
		&i.WeekStart,
		&i.Adherence,
		&i.WeightChange,
		&i.NewTargetsJson,
		&i.Explanation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNutritionDailyCheckinByUserIDAndDate = `-- name: GetNutritionDailyCheckinByUserIDAndDate :one
SELECT id, user_id, date, calories_estimate, protein_g_estimate, hit_calories, hit_protein, notes, created_at
FROM nutrition_daily_checkins
WHERE user_id = $1
  AND date = $2
LIMIT 1
`

type GetNutritionDailyCheckinByUserIDAndDateParams struct {
	UserID uuid.UUID `json:"user_id"`
	Date   time.Time `json:"date"`
}

func (q *Queries) GetNutritionDailyCheckinByUserIDAndDate(ctx context.Context, arg GetNutritionDailyCheckinByUserIDAndDateParams) (NutritionDailyCheckin, error) {
	row := q.db.QueryRowContext(ctx, getNutritionDailyCheckinByUserIDAndDate, arg.UserID, arg.Date)
	var i NutritionDailyCheckin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.CaloriesEstimate,
		&i.ProteinGEstimate,
		&i.HitCalories,
		&i.HitProtein,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getNutritionTargetsByUserID = `-- name: GetNutritionTargetsByUserID :one
SELECT user_id, calories_target, protein_g_target, created_at, updated_at
FROM nutrition_targets
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetNutritionTargetsByUserID(ctx context.Context, userID uuid.UUID) (NutritionTarget, error) {
	row := q.db.QueryRowContext(ctx, getNutritionTargetsByUserID, userID)
	var i NutritionTarget
	err := row.Scan(
		&i.UserID,
		&i.CaloriesTarget,
		&i.ProteinGTarget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWeeklyCheckinByUserIDAndWeekStart = `-- name: GetWeeklyCheckinByUserIDAndWeekStart :one
SELECT user_id, week_start, adherence, weight_change, new_targets_json, explanation, created_at, updated_at
FROM weekly_checkins
WHERE user_id = $1
  AND week_start = $2
LIMIT 1
`

type GetWeeklyCheckinByUserIDAndWeekStartParams struct {
	UserID    uuid.UUID `json:"user_id"`
	WeekStart time.Time `json:"week_start"`
}

func (q *Queries) GetWeeklyCheckinByUserIDAndWeekStart(ctx context.Context, arg GetWeeklyCheckinByUserIDAndWeekStartParams) (WeeklyCheckin, error) {
	row := q.db.QueryRowContext(ctx, getWeeklyCheckinByUserIDAndWeekStart, arg.UserID, arg.WeekStart)
	var i WeeklyCheckin
	err := row.Scan(
		&i.UserID,
		&i.WeekStart,
		&i.Adherence,
		&i.WeightChange,
		&i.NewTargetsJson,
		&i.Explanation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNutritionDailyCheckinsByDateRange = `-- name: ListNutritionDailyCheckinsByDateRange :many
SELECT id, user_id, date, calories_estimate, protein_g_estimate, hit_calories, hit_protein, notes, created_at
FROM nutrition_daily_checkins
WHERE user_id = $1
  AND date >= $2
  AND date < $3
ORDER BY date ASC
`

type ListNutritionDailyCheckinsByDateRangeParams struct {
	UserID    uuid.UUID `json:"user_id"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

func (q *Queries) ListNutritionDailyCheckinsByDateRange(ctx context.Context, arg ListNutritionDailyCheckinsByDateRangeParams) ([]NutritionDailyCheckin, error) {
	rows, err := q.db.QueryContext(ctx, listNutritionDailyCheckinsByDateRange, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NutritionDailyCheckin{}
	for rows.Next() {
		var i NutritionDailyCheckin
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.CaloriesEstimate,
			&i.ProteinGEstimate,
			&i.HitCalories,
			&i.HitProtein,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNutritionWeightTrend = `-- name: ListNutritionWeightTrend :many
WITH bounds AS (
    SELECT DATE_TRUNC('week', $1::timestamp)::date AS current_week_start
),
week_series AS (
    SELECT generate_series(
        (SELECT current_week_start FROM bounds) - INTERVAL '7 weeks',
        (SELECT current_week_start FROM bounds),
        INTERVAL '1 week'
    )::date AS week_start_date
),
weekly_latest AS (
    SELECT DISTINCT ON (DATE_TRUNC('week', uwe.date::timestamp)::date)
        DATE_TRUNC('week', uwe.date::timestamp)::date AS week_start_date,
        uwe.date AS entry_date,
        uwe.weight_kg,
        uwe.unit,
        uwe.updated_at
    FROM user_weight_entries uwe
    JOIN bounds b ON true
    WHERE uwe.user_id = $2
      AND uwe.date >= (b.current_week_start - INTERVAL '7 weeks')
      AND uwe.date < (b.current_week_start + INTERVAL '1 week')
    ORDER BY DATE_TRUNC('week', uwe.date::timestamp)::date ASC, uwe.date DESC, uwe.updated_at DESC
)
SELECT
    ws.week_start_date,
    COALESCE((wl.entry_date IS NOT NULL), FALSE)::boolean AS has_entry,
    COALESCE(wl.entry_date, DATE '0001-01-01')::date AS entry_date,
    COALESCE(wl.weight_kg, 0.0)::double precision AS weight_kg,
    COALESCE(wl.unit, 'kg')::text AS unit
FROM week_series ws
LEFT JOIN weekly_latest wl ON wl.week_start_date = ws.week_start_date
ORDER BY ws.week_start_date ASC
`

type ListNutritionWeightTrendParams struct {
	AnchorDate time.Time `json:"anchor_date"`
	UserID     uuid.UUID `json:"user_id"`
}

type ListNutritionWeightTrendRow struct {
	WeekStartDate time.Time `json:"week_start_date"`
	HasEntry      bool      `json:"has_entry"`
	EntryDate     time.Time `json:"entry_date"`
	WeightKg      float64   `json:"weight_kg"`
	Unit          string    `json:"unit"`
}

func (q *Queries) ListNutritionWeightTrend(ctx context.Context, arg ListNutritionWeightTrendParams) ([]ListNutritionWeightTrendRow, error) {
	rows, err := q.db.QueryContext(ctx, listNutritionWeightTrend, arg.AnchorDate, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNutritionWeightTrendRow{}
	for rows.Next() {
		var i ListNutritionWeightTrendRow
		if err := rows.Scan(
			&i.WeekStartDate,
			&i.HasEntry,
			&i.EntryDate,
			&i.WeightKg,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNutritionDailyCheckin = `-- name: UpsertNutritionDailyCheckin :one
INSERT INTO nutrition_daily_checkins (
    user_id,
    date,
    calories_estimate,
    protein_g_estimate,
    hit_calories,
    hit_protein,
    notes
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (user_id, date)
DO UPDATE SET
    calories_estimate = EXCLUDED.calories_estimate,
    protein_g_estimate = EXCLUDED.protein_g_estimate,
    hit_calories = EXCLUDED.hit_calories,
    hit_protein = EXCLUDED.hit_protein,
    notes = EXCLUDED.notes
RETURNING id, user_id, date, calories_estimate, protein_g_estimate, hit_calories, hit_protein, notes, created_at
`

type UpsertNutritionDailyCheckinParams struct {
	UserID           uuid.UUID     `json:"user_id"`
	Date             time.Time     `json:"date"`
	CaloriesEstimate sql.NullInt32 `json:"calories_estimate"`
	ProteinGEstimate sql.NullInt32 `json:"protein_g_estimate"`
	HitCalories      bool          `json:"hit_calories"`
	HitProtein       bool          `json:"hit_protein"`
	Notes            string        `json:"notes"`
}

func (q *Queries) UpsertNutritionDailyCheckin(ctx context.Context, arg UpsertNutritionDailyCheckinParams) (NutritionDailyCheckin, error) {
	row := q.db.QueryRowContext(ctx, upsertNutritionDailyCheckin,
		arg.UserID,
		arg.Date,
		arg.CaloriesEstimate,
		arg.ProteinGEstimate,
		arg.HitCalories,
		arg.HitProtein,
		arg.Notes,
	)
	var i NutritionDailyCheckin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.CaloriesEstimate,
		&i.ProteinGEstimate,
		&i.HitCalories,
		&i.HitProtein,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const upsertNutritionTargets = `-- name: UpsertNutritionTargets :one
INSERT INTO nutrition_targets (
    user_id,
    calories_target,
    protein_g_target
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (user_id)
DO UPDATE SET
    calories_target = EXCLUDED.calories_target,
    protein_g_target = EXCLUDED.protein_g_target,
    updated_at = NOW()
RETURNING user_id, calories_target, protein_g_target, created_at, updated_at
`

type UpsertNutritionTargetsParams struct {
	UserID         uuid.UUID `json:"user_id"`
	CaloriesTarget int32     `json:"calories_target"`
	ProteinGTarget int32     `json:"protein_g_target"`
}

func (q *Queries) UpsertNutritionTargets(ctx context.Context, arg UpsertNutritionTargetsParams) (NutritionTarget, error) {
	row := q.db.QueryRowContext(ctx, upsertNutritionTargets, arg.UserID, arg.CaloriesTarget, arg.ProteinGTarget)
	var i NutritionTarget
	err := row.Scan(
		&i.UserID,
		&i.CaloriesTarget,
		&i.ProteinGTarget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserWeightEntry = `-- name: UpsertUserWeightEntry :one
INSERT INTO user_weight_entries (
    user_id,
    date,
    weight_kg,
    unit
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (user_id, date)
DO UPDATE SET
    weight_kg = EXCLUDED.weight_kg,
    unit = EXCLUDED.unit,
    updated_at = NOW()
RETURNING user_id, date, weight_kg, unit, created_at, updated_at
`

type UpsertUserWeightEntryParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Date     time.Time `json:"date"`
	WeightKg float64   `json:"weight_kg"`
	Unit     string    `json:"unit"`
}

func (q *Queries) UpsertUserWeightEntry(ctx context.Context, arg UpsertUserWeightEntryParams) (UserWeightEntry, error) {
	row := q.db.QueryRowContext(ctx, upsertUserWeightEntry,
		arg.UserID,
		arg.Date,
		arg.WeightKg,
		arg.Unit,
	)
	var i UserWeightEntry
	err := row.Scan(
		&i.UserID,
		&i.Date,
		&i.WeightKg,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWeeklyCheckin = `-- name: UpsertWeeklyCheckin :one
INSERT INTO weekly_checkins (
    user_id,
    week_start,
    adherence,
    weight_change,
    new_targets_json,
    explanation
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (user_id, week_start)
DO UPDATE SET
    adherence = EXCLUDED.adherence,
    weight_change = EXCLUDED.weight_change,
    new_targets_json = EXCLUDED.new_targets_json,
    explanation = EXCLUDED.explanation,
    updated_at = NOW()
RETURNING user_id, week_start, adherence, weight_change, new_targets_json, explanation, created_at, updated_at
`

type UpsertWeeklyCheckinParams struct {
	UserID         uuid.UUID       `json:"user_id"`
	WeekStart      time.Time       `json:"week_start"`
	Adherence      float64         `json:"adherence"`
	WeightChange   float64         `json:"weight_change"`
	NewTargetsJson json.RawMessage `json:"new_targets_json"`
	Explanation    string          `json:"explanation"`
}

func (q *Queries) UpsertWeeklyCheckin(ctx context.Context, arg UpsertWeeklyCheckinParams) (WeeklyCheckin, error) {
	row := q.db.QueryRowContext(ctx, upsertWeeklyCheckin,
		arg.UserID,
		arg.WeekStart,
		arg.Adherence,
		arg.WeightChange,
		arg.NewTargetsJson,
		arg.Explanation,
	)
	var i WeeklyCheckin
	err := row.Scan(
		&i.UserID,
		&i.WeekStart,
		&i.Adherence,
		&i.WeightChange,
		&i.NewTargetsJson,
		&i.Explanation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
