// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: onboarding.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const getOnboardingStatus = `-- name: GetOnboardingStatus :one
SELECT
    EXISTS(SELECT 1 FROM user_profiles up WHERE up.user_id = $1) AS has_profile,
    EXISTS(SELECT 1 FROM user_goals ug WHERE ug.user_id = $1) AS has_goals
`

type GetOnboardingStatusRow struct {
	HasProfile bool `json:"has_profile"`
	HasGoals   bool `json:"has_goals"`
}

func (q *Queries) GetOnboardingStatus(ctx context.Context, userID uuid.UUID) (GetOnboardingStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getOnboardingStatus, userID)
	var i GetOnboardingStatusRow
	err := row.Scan(&i.HasProfile, &i.HasGoals)
	return i, err
}

const getUserGoalsByUserID = `-- name: GetUserGoalsByUserID :one
SELECT user_id, primary_goal, secondary_goal, days_per_week, session_duration_minutes, equipment_access_json, constraints_json, injuries_limitations_json, modality_preferences_json, prior_training_history_json, readiness_signals_json, created_at, updated_at
FROM user_goals
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetUserGoalsByUserID(ctx context.Context, userID uuid.UUID) (UserGoal, error) {
	row := q.db.QueryRowContext(ctx, getUserGoalsByUserID, userID)
	var i UserGoal
	err := row.Scan(
		&i.UserID,
		&i.PrimaryGoal,
		&i.SecondaryGoal,
		&i.DaysPerWeek,
		&i.SessionDurationMinutes,
		&i.EquipmentAccessJson,
		&i.ConstraintsJson,
		&i.InjuriesLimitationsJson,
		&i.ModalityPreferencesJson,
		&i.PriorTrainingHistoryJson,
		&i.ReadinessSignalsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfileByUserID = `-- name: GetUserProfileByUserID :one
SELECT user_id, display_name, sex, height_cm, weight_kg, experience_level, created_at, updated_at
FROM user_profiles
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetUserProfileByUserID(ctx context.Context, userID uuid.UUID) (UserProfile, error) {
	row := q.db.QueryRowContext(ctx, getUserProfileByUserID, userID)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Sex,
		&i.HeightCm,
		&i.WeightKg,
		&i.ExperienceLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserGoals = `-- name: UpsertUserGoals :one
INSERT INTO user_goals (
    user_id,
    primary_goal,
    secondary_goal,
    days_per_week,
    session_duration_minutes,
    equipment_access_json,
    constraints_json,
    injuries_limitations_json,
    modality_preferences_json,
    prior_training_history_json,
    readiness_signals_json
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
ON CONFLICT (user_id)
DO UPDATE SET
    primary_goal = EXCLUDED.primary_goal,
    secondary_goal = EXCLUDED.secondary_goal,
    days_per_week = EXCLUDED.days_per_week,
    session_duration_minutes = EXCLUDED.session_duration_minutes,
    equipment_access_json = EXCLUDED.equipment_access_json,
    constraints_json = EXCLUDED.constraints_json,
    injuries_limitations_json = EXCLUDED.injuries_limitations_json,
    modality_preferences_json = EXCLUDED.modality_preferences_json,
    prior_training_history_json = EXCLUDED.prior_training_history_json,
    readiness_signals_json = EXCLUDED.readiness_signals_json,
    updated_at = NOW()
RETURNING user_id, primary_goal, secondary_goal, days_per_week, session_duration_minutes, equipment_access_json, constraints_json, injuries_limitations_json, modality_preferences_json, prior_training_history_json, readiness_signals_json, created_at, updated_at
`

type UpsertUserGoalsParams struct {
	UserID                   uuid.UUID             `json:"user_id"`
	PrimaryGoal              string                `json:"primary_goal"`
	SecondaryGoal            sql.NullString        `json:"secondary_goal"`
	DaysPerWeek              int32                 `json:"days_per_week"`
	SessionDurationMinutes   int32                 `json:"session_duration_minutes"`
	EquipmentAccessJson      json.RawMessage       `json:"equipment_access_json"`
	ConstraintsJson          json.RawMessage       `json:"constraints_json"`
	InjuriesLimitationsJson  json.RawMessage       `json:"injuries_limitations_json"`
	ModalityPreferencesJson  json.RawMessage       `json:"modality_preferences_json"`
	PriorTrainingHistoryJson pqtype.NullRawMessage `json:"prior_training_history_json"`
	ReadinessSignalsJson     pqtype.NullRawMessage `json:"readiness_signals_json"`
}

func (q *Queries) UpsertUserGoals(ctx context.Context, arg UpsertUserGoalsParams) (UserGoal, error) {
	row := q.db.QueryRowContext(ctx, upsertUserGoals,
		arg.UserID,
		arg.PrimaryGoal,
		arg.SecondaryGoal,
		arg.DaysPerWeek,
		arg.SessionDurationMinutes,
		arg.EquipmentAccessJson,
		arg.ConstraintsJson,
		arg.InjuriesLimitationsJson,
		arg.ModalityPreferencesJson,
		arg.PriorTrainingHistoryJson,
		arg.ReadinessSignalsJson,
	)
	var i UserGoal
	err := row.Scan(
		&i.UserID,
		&i.PrimaryGoal,
		&i.SecondaryGoal,
		&i.DaysPerWeek,
		&i.SessionDurationMinutes,
		&i.EquipmentAccessJson,
		&i.ConstraintsJson,
		&i.InjuriesLimitationsJson,
		&i.ModalityPreferencesJson,
		&i.PriorTrainingHistoryJson,
		&i.ReadinessSignalsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserProfile = `-- name: UpsertUserProfile :one
INSERT INTO user_profiles (
    user_id,
    display_name,
    sex,
    height_cm,
    weight_kg,
    experience_level
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (user_id)
DO UPDATE SET
    display_name = EXCLUDED.display_name,
    sex = EXCLUDED.sex,
    height_cm = EXCLUDED.height_cm,
    weight_kg = EXCLUDED.weight_kg,
    experience_level = EXCLUDED.experience_level,
    updated_at = NOW()
RETURNING user_id, display_name, sex, height_cm, weight_kg, experience_level, created_at, updated_at
`

type UpsertUserProfileParams struct {
	UserID          uuid.UUID `json:"user_id"`
	DisplayName     string    `json:"display_name"`
	Sex             string    `json:"sex"`
	HeightCm        int32     `json:"height_cm"`
	WeightKg        float64   `json:"weight_kg"`
	ExperienceLevel string    `json:"experience_level"`
}

func (q *Queries) UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRowContext(ctx, upsertUserProfile,
		arg.UserID,
		arg.DisplayName,
		arg.Sex,
		arg.HeightCm,
		arg.WeightKg,
		arg.ExperienceLevel,
	)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Sex,
		&i.HeightCm,
		&i.WeightKg,
		&i.ExperienceLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
