// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: programs.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getProgramByID = `-- name: GetProgramByID :one
SELECT id, slug, name, description, goal_tags_json, level, weeks_length, created_at
FROM programs
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProgramByID(ctx context.Context, id uuid.UUID) (Program, error) {
	row := q.db.QueryRowContext(ctx, getProgramByID, id)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.GoalTagsJson,
		&i.Level,
		&i.WeeksLength,
		&i.CreatedAt,
	)
	return i, err
}

const getProgramWeekByProgramIDAndWeekIndex = `-- name: GetProgramWeekByProgramIDAndWeekIndex :one
SELECT id, program_id, week_index, created_at
FROM program_weeks
WHERE program_id = $1
  AND week_index = $2
LIMIT 1
`

type GetProgramWeekByProgramIDAndWeekIndexParams struct {
	ProgramID uuid.UUID `json:"program_id"`
	WeekIndex int32     `json:"week_index"`
}

func (q *Queries) GetProgramWeekByProgramIDAndWeekIndex(ctx context.Context, arg GetProgramWeekByProgramIDAndWeekIndexParams) (ProgramWeek, error) {
	row := q.db.QueryRowContext(ctx, getProgramWeekByProgramIDAndWeekIndex, arg.ProgramID, arg.WeekIndex)
	var i ProgramWeek
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.WeekIndex,
		&i.CreatedAt,
	)
	return i, err
}

const getUserProgramEnrollmentByUserID = `-- name: GetUserProgramEnrollmentByUserID :one
SELECT id, user_id, program_id, start_date, current_week, created_at
FROM user_program_enrollments
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetUserProgramEnrollmentByUserID(ctx context.Context, userID uuid.UUID) (UserProgramEnrollment, error) {
	row := q.db.QueryRowContext(ctx, getUserProgramEnrollmentByUserID, userID)
	var i UserProgramEnrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProgramID,
		&i.StartDate,
		&i.CurrentWeek,
		&i.CreatedAt,
	)
	return i, err
}

const listProgramBlocksByProgramID = `-- name: ListProgramBlocksByProgramID :many
SELECT
    pw.id,
    pw.program_id,
    pw.week_index,
    COALESCE(
        array_agg(ps.day_of_week ORDER BY ps.day_of_week) FILTER (WHERE ps.id IS NOT NULL),
        ARRAY[]::int[]
    )::int[] AS session_days,
    COUNT(ps.id)::int AS session_count
FROM program_weeks pw
LEFT JOIN program_sessions ps ON ps.program_week_id = pw.id
WHERE pw.program_id = $1
GROUP BY pw.id, pw.program_id, pw.week_index
ORDER BY pw.week_index ASC
`

type ListProgramBlocksByProgramIDRow struct {
	ID           uuid.UUID `json:"id"`
	ProgramID    uuid.UUID `json:"program_id"`
	WeekIndex    int32     `json:"week_index"`
	SessionDays  []int32   `json:"session_days"`
	SessionCount int32     `json:"session_count"`
}

func (q *Queries) ListProgramBlocksByProgramID(ctx context.Context, programID uuid.UUID) ([]ListProgramBlocksByProgramIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listProgramBlocksByProgramID, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramBlocksByProgramIDRow{}
	for rows.Next() {
		var i ListProgramBlocksByProgramIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.WeekIndex,
			pq.Array(&i.SessionDays),
			&i.SessionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramSessionExercisesByProgramSessionID = `-- name: ListProgramSessionExercisesByProgramSessionID :many
SELECT
    pse.id,
    pse.program_session_id,
    pse.exercise_id,
    pse.prescription_json,
    pse.order_index,
    e.slug AS exercise_slug,
    e.name AS exercise_name
FROM program_session_exercises pse
JOIN exercises e ON e.id = pse.exercise_id
WHERE pse.program_session_id = $1
ORDER BY pse.order_index ASC
`

type ListProgramSessionExercisesByProgramSessionIDRow struct {
	ID               uuid.UUID       `json:"id"`
	ProgramSessionID uuid.UUID       `json:"program_session_id"`
	ExerciseID       uuid.UUID       `json:"exercise_id"`
	PrescriptionJson json.RawMessage `json:"prescription_json"`
	OrderIndex       int32           `json:"order_index"`
	ExerciseSlug     string          `json:"exercise_slug"`
	ExerciseName     string          `json:"exercise_name"`
}

func (q *Queries) ListProgramSessionExercisesByProgramSessionID(ctx context.Context, programSessionID uuid.UUID) ([]ListProgramSessionExercisesByProgramSessionIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listProgramSessionExercisesByProgramSessionID, programSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramSessionExercisesByProgramSessionIDRow{}
	for rows.Next() {
		var i ListProgramSessionExercisesByProgramSessionIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramSessionID,
			&i.ExerciseID,
			&i.PrescriptionJson,
			&i.OrderIndex,
			&i.ExerciseSlug,
			&i.ExerciseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramSessionsByProgramWeekID = `-- name: ListProgramSessionsByProgramWeekID :many
SELECT id, program_week_id, day_of_week, name, created_at
FROM program_sessions
WHERE program_week_id = $1
ORDER BY day_of_week ASC
`

func (q *Queries) ListProgramSessionsByProgramWeekID(ctx context.Context, programWeekID uuid.UUID) ([]ProgramSession, error) {
	rows, err := q.db.QueryContext(ctx, listProgramSessionsByProgramWeekID, programWeekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProgramSession{}
	for rows.Next() {
		var i ProgramSession
		if err := rows.Scan(
			&i.ID,
			&i.ProgramWeekID,
			&i.DayOfWeek,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramSubstitutionCandidates = `-- name: ListProgramSubstitutionCandidates :many
WITH prescribed AS (
    SELECT id, movement_pattern
    FROM exercises
    WHERE exercises.id = $3
)
SELECT
    e.id,
    e.slug,
    e.name,
    e.movement_pattern,
    e.equipment_json
FROM prescribed p
JOIN exercises e ON e.movement_pattern = p.movement_pattern
WHERE e.id <> p.id
  AND (
    cardinality($1::text[]) = 0
    OR e.equipment_json ?| $1::text[]
  )
ORDER BY e.name ASC
LIMIT $2
`

type ListProgramSubstitutionCandidatesParams struct {
	Equipment  []string  `json:"equipment"`
	MaxCount   int32     `json:"max_count"`
	ExerciseID uuid.UUID `json:"exercise_id"`
}

type ListProgramSubstitutionCandidatesRow struct {
	ID              uuid.UUID       `json:"id"`
	Slug            string          `json:"slug"`
	Name            string          `json:"name"`
	MovementPattern string          `json:"movement_pattern"`
	EquipmentJson   json.RawMessage `json:"equipment_json"`
}

func (q *Queries) ListProgramSubstitutionCandidates(ctx context.Context, arg ListProgramSubstitutionCandidatesParams) ([]ListProgramSubstitutionCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listProgramSubstitutionCandidates, pq.Array(arg.Equipment), arg.MaxCount, arg.ExerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramSubstitutionCandidatesRow{}
	for rows.Next() {
		var i ListProgramSubstitutionCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.MovementPattern,
			&i.EquipmentJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrograms = `-- name: ListPrograms :many
SELECT id, slug, name, description, goal_tags_json, level, weeks_length, created_at
FROM programs
ORDER BY name ASC
`

func (q *Queries) ListPrograms(ctx context.Context) ([]Program, error) {
	rows, err := q.db.QueryContext(ctx, listPrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Program{}
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.GoalTagsJson,
			&i.Level,
			&i.WeeksLength,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserProgramEnrollment = `-- name: UpsertUserProgramEnrollment :one
INSERT INTO user_program_enrollments (
    user_id,
    program_id,
    start_date,
    current_week
) VALUES (
    $1,
    $2,
    $3,
    1
)
ON CONFLICT (user_id)
DO UPDATE SET
    program_id = EXCLUDED.program_id,
    start_date = EXCLUDED.start_date,
    current_week = 1,
    created_at = NOW()
RETURNING id, user_id, program_id, start_date, current_week, created_at
`

type UpsertUserProgramEnrollmentParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ProgramID uuid.UUID `json:"program_id"`
	StartDate time.Time `json:"start_date"`
}

func (q *Queries) UpsertUserProgramEnrollment(ctx context.Context, arg UpsertUserProgramEnrollmentParams) (UserProgramEnrollment, error) {
	row := q.db.QueryRowContext(ctx, upsertUserProgramEnrollment, arg.UserID, arg.ProgramID, arg.StartDate)
	var i UserProgramEnrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProgramID,
		&i.StartDate,
		&i.CurrentWeek,
		&i.CreatedAt,
	)
	return i, err
}
