// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: progression.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const getUserExerciseProgressByUserIDAndExerciseID = `-- name: GetUserExerciseProgressByUserIDAndExerciseID :one
SELECT user_id, exercise_id, last_load, last_reps, last_rpe, updated_at
FROM user_exercise_progress
WHERE user_id = $1
  AND exercise_id = $2
LIMIT 1
`

type GetUserExerciseProgressByUserIDAndExerciseIDParams struct {
	UserID     uuid.UUID `json:"user_id"`
	ExerciseID uuid.UUID `json:"exercise_id"`
}

func (q *Queries) GetUserExerciseProgressByUserIDAndExerciseID(ctx context.Context, arg GetUserExerciseProgressByUserIDAndExerciseIDParams) (UserExerciseProgress, error) {
	row := q.db.QueryRowContext(ctx, getUserExerciseProgressByUserIDAndExerciseID, arg.UserID, arg.ExerciseID)
	var i UserExerciseProgress
	err := row.Scan(
		&i.UserID,
		&i.ExerciseID,
		&i.LastLoad,
		&i.LastReps,
		&i.LastRpe,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProgramStateByUserIDAndProgramID = `-- name: GetUserProgramStateByUserIDAndProgramID :one
SELECT
    user_id,
    program_id,
    current_week,
    deload_flag,
    last_week_adherence,
    last_week_scheduled_sessions,
    last_week_completed_sessions,
    last_week_density,
    last_week_high_rpe_rate,
    fatigue_score,
    consecutive_low_adherence_weeks,
    adjustment_reasons_json,
    updated_at
FROM user_program_state
WHERE user_id = $1
  AND program_id = $2
LIMIT 1
`

type GetUserProgramStateByUserIDAndProgramIDParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ProgramID uuid.UUID `json:"program_id"`
}

func (q *Queries) GetUserProgramStateByUserIDAndProgramID(ctx context.Context, arg GetUserProgramStateByUserIDAndProgramIDParams) (UserProgramState, error) {
	row := q.db.QueryRowContext(ctx, getUserProgramStateByUserIDAndProgramID, arg.UserID, arg.ProgramID)
	var i UserProgramState
	err := row.Scan(
		&i.UserID,
		&i.ProgramID,
		&i.CurrentWeek,
		&i.DeloadFlag,
		&i.LastWeekAdherence,
		&i.LastWeekScheduledSessions,
		&i.LastWeekCompletedSessions,
		&i.LastWeekDensity,
		&i.LastWeekHighRpeRate,
		&i.FatigueScore,
		&i.ConsecutiveLowAdherenceWeeks,
		&i.AdjustmentReasonsJson,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserExerciseProgress = `-- name: UpsertUserExerciseProgress :exec
INSERT INTO user_exercise_progress (
    user_id,
    exercise_id,
    last_load,
    last_reps,
    last_rpe
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (user_id, exercise_id)
DO UPDATE SET
    last_load = EXCLUDED.last_load,
    last_reps = EXCLUDED.last_reps,
    last_rpe = EXCLUDED.last_rpe,
    updated_at = NOW()
`

type UpsertUserExerciseProgressParams struct {
	UserID     uuid.UUID       `json:"user_id"`
	ExerciseID uuid.UUID       `json:"exercise_id"`
	LastLoad   float64         `json:"last_load"`
	LastReps   int32           `json:"last_reps"`
	LastRpe    sql.NullFloat64 `json:"last_rpe"`
}

func (q *Queries) UpsertUserExerciseProgress(ctx context.Context, arg UpsertUserExerciseProgressParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserExerciseProgress,
		arg.UserID,
		arg.ExerciseID,
		arg.LastLoad,
		arg.LastReps,
		arg.LastRpe,
	)
	return err
}

const upsertUserProgramState = `-- name: UpsertUserProgramState :exec
INSERT INTO user_program_state (
    user_id,
    program_id,
    current_week,
    deload_flag,
    last_week_adherence,
    last_week_scheduled_sessions,
    last_week_completed_sessions,
    last_week_density,
    last_week_high_rpe_rate,
    fatigue_score,
    consecutive_low_adherence_weeks,
    adjustment_reasons_json
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
ON CONFLICT (user_id, program_id)
DO UPDATE SET
    current_week = EXCLUDED.current_week,
    deload_flag = EXCLUDED.deload_flag,
    last_week_adherence = EXCLUDED.last_week_adherence,
    last_week_scheduled_sessions = EXCLUDED.last_week_scheduled_sessions,
    last_week_completed_sessions = EXCLUDED.last_week_completed_sessions,
    last_week_density = EXCLUDED.last_week_density,
    last_week_high_rpe_rate = EXCLUDED.last_week_high_rpe_rate,
    fatigue_score = EXCLUDED.fatigue_score,
    consecutive_low_adherence_weeks = EXCLUDED.consecutive_low_adherence_weeks,
    adjustment_reasons_json = EXCLUDED.adjustment_reasons_json,
    updated_at = NOW()
`

type UpsertUserProgramStateParams struct {
	UserID                       uuid.UUID       `json:"user_id"`
	ProgramID                    uuid.UUID       `json:"program_id"`
	CurrentWeek                  int32           `json:"current_week"`
	DeloadFlag                   bool            `json:"deload_flag"`
	LastWeekAdherence            float64         `json:"last_week_adherence"`
	LastWeekScheduledSessions    int32           `json:"last_week_scheduled_sessions"`
	LastWeekCompletedSessions    int32           `json:"last_week_completed_sessions"`
	LastWeekDensity              float64         `json:"last_week_density"`
	LastWeekHighRpeRate          float64         `json:"last_week_high_rpe_rate"`
	FatigueScore                 float64         `json:"fatigue_score"`
	ConsecutiveLowAdherenceWeeks int32           `json:"consecutive_low_adherence_weeks"`
	AdjustmentReasonsJson        json.RawMessage `json:"adjustment_reasons_json"`
}

func (q *Queries) UpsertUserProgramState(ctx context.Context, arg UpsertUserProgramStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserProgramState,
		arg.UserID,
		arg.ProgramID,
		arg.CurrentWeek,
		arg.DeloadFlag,
		arg.LastWeekAdherence,
		arg.LastWeekScheduledSessions,
		arg.LastWeekCompletedSessions,
		arg.LastWeekDensity,
		arg.LastWeekHighRpeRate,
		arg.FatigueScore,
		arg.ConsecutiveLowAdherenceWeeks,
		arg.AdjustmentReasonsJson,
	)
	return err
}
