// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: readiness.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const upsertReadinessCheckin = `-- name: UpsertReadinessCheckin :one
INSERT INTO readiness_checkins (
    user_id,
    date,
    energy_level,
    sleep_quality,
    stress_level,
    readiness_score
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    (
        (
            $3::integer
            + $4::integer
            + (4 - $5::integer)
        )::double precision / 3.0
    )::double precision
)
ON CONFLICT (user_id, date)
DO UPDATE SET
    energy_level = EXCLUDED.energy_level,
    sleep_quality = EXCLUDED.sleep_quality,
    stress_level = EXCLUDED.stress_level,
    readiness_score = EXCLUDED.readiness_score,
    updated_at = NOW()
RETURNING
    user_id,
    date,
    energy_level,
    sleep_quality,
    stress_level,
    readiness_score,
    created_at,
    updated_at
`

type UpsertReadinessCheckinParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Date         time.Time `json:"date"`
	EnergyLevel  int32     `json:"energy_level"`
	SleepQuality int32     `json:"sleep_quality"`
	StressLevel  int32     `json:"stress_level"`
}

func (q *Queries) UpsertReadinessCheckin(ctx context.Context, arg UpsertReadinessCheckinParams) (ReadinessCheckin, error) {
	row := q.db.QueryRowContext(ctx, upsertReadinessCheckin,
		arg.UserID,
		arg.Date,
		arg.EnergyLevel,
		arg.SleepQuality,
		arg.StressLevel,
	)
	var i ReadinessCheckin
	err := row.Scan(
		&i.UserID,
		&i.Date,
		&i.EnergyLevel,
		&i.SleepQuality,
		&i.StressLevel,
		&i.ReadinessScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
