// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    user_id,
    refresh_token_hash,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, user_id, refresh_token_hash, expires_at, created_at, revoked_at
`

type CreateSessionParams struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	RefreshTokenHash string    `json:"refresh_token_hash"`
	ExpiresAt        time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveSessionByRefreshTokenHash = `-- name: GetActiveSessionByRefreshTokenHash :one
SELECT id, user_id, refresh_token_hash, expires_at, created_at, revoked_at
FROM sessions
WHERE refresh_token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetActiveSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getActiveSessionByRefreshTokenHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeSessionByID = `-- name: RevokeSessionByID :execrows
UPDATE sessions
SET revoked_at = COALESCE(revoked_at, NOW())
WHERE id = $1
`

func (q *Queries) RevokeSessionByID(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeSessionByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeSessionByRefreshTokenHash = `-- name: RevokeSessionByRefreshTokenHash :execrows
UPDATE sessions
SET revoked_at = COALESCE(revoked_at, NOW())
WHERE refresh_token_hash = $1
`

func (q *Queries) RevokeSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeSessionByRefreshTokenHash, refreshTokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
