// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: subscriptions.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const listSubscriptionsByUserID = `-- name: ListSubscriptionsByUserID :many
SELECT
    id,
    user_id,
    platform,
    product_id,
    status,
    expires_at,
    raw_receipt,
    transaction_id,
    original_transaction_id,
    created_at,
    updated_at
FROM subscriptions
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSubscriptionsByUserID(ctx context.Context, userID uuid.UUID) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.ProductID,
			&i.Status,
			&i.ExpiresAt,
			&i.RawReceipt,
			&i.TransactionID,
			&i.OriginalTransactionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserEntitlements = `-- name: ListUserEntitlements :many
SELECT entitlement
FROM user_entitlements
WHERE user_id = $1
ORDER BY entitlement
`

func (q *Queries) ListUserEntitlements(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUserEntitlements, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var entitlement string
		if err := rows.Scan(&entitlement); err != nil {
			return nil, err
		}
		items = append(items, entitlement)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSubscription = `-- name: UpsertSubscription :one
INSERT INTO subscriptions (
    user_id,
    platform,
    product_id,
    status,
    expires_at,
    raw_receipt,
    transaction_id,
    original_transaction_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
ON CONFLICT (user_id, platform, transaction_id)
DO UPDATE SET
    product_id = EXCLUDED.product_id,
    status = EXCLUDED.status,
    expires_at = EXCLUDED.expires_at,
    raw_receipt = EXCLUDED.raw_receipt,
    original_transaction_id = COALESCE(EXCLUDED.original_transaction_id, subscriptions.original_transaction_id),
    updated_at = NOW()
RETURNING
    id,
    user_id,
    platform,
    product_id,
    status,
    expires_at,
    raw_receipt,
    transaction_id,
    original_transaction_id,
    created_at,
    updated_at
`

type UpsertSubscriptionParams struct {
	UserID                uuid.UUID       `json:"user_id"`
	Platform              string          `json:"platform"`
	ProductID             string          `json:"product_id"`
	Status                string          `json:"status"`
	ExpiresAt             sql.NullTime    `json:"expires_at"`
	RawReceipt            json.RawMessage `json:"raw_receipt"`
	TransactionID         string          `json:"transaction_id"`
	OriginalTransactionID sql.NullString  `json:"original_transaction_id"`
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, upsertSubscription,
		arg.UserID,
		arg.Platform,
		arg.ProductID,
		arg.Status,
		arg.ExpiresAt,
		arg.RawReceipt,
		arg.TransactionID,
		arg.OriginalTransactionID,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.ProductID,
		&i.Status,
		&i.ExpiresAt,
		&i.RawReceipt,
		&i.TransactionID,
		&i.OriginalTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
