// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workouts.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const completeWorkout = `-- name: CompleteWorkout :one
UPDATE workouts
SET completed_at = $3,
    notes = $4
WHERE id = $1
  AND user_id = $2
  AND completed_at IS NULL
RETURNING id, user_id, program_session_id, started_at, completed_at, notes, created_at
`

type CompleteWorkoutParams struct {
	ID          uuid.UUID    `json:"id"`
	UserID      uuid.UUID    `json:"user_id"`
	CompletedAt sql.NullTime `json:"completed_at"`
	Notes       string       `json:"notes"`
}

func (q *Queries) CompleteWorkout(ctx context.Context, arg CompleteWorkoutParams) (Workout, error) {
	row := q.db.QueryRowContext(ctx, completeWorkout,
		arg.ID,
		arg.UserID,
		arg.CompletedAt,
		arg.Notes,
	)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProgramSessionID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const countCompletedProgramWorkoutSetsBetween = `-- name: CountCompletedProgramWorkoutSetsBetween :one
SELECT COUNT(ws.id)::int
FROM workouts w
JOIN program_sessions ps ON ps.id = w.program_session_id
JOIN program_weeks pw ON pw.id = ps.program_week_id
JOIN workout_exercises we ON we.workout_id = w.id
JOIN workout_sets ws ON ws.workout_exercise_id = we.id
WHERE w.user_id = $1
  AND pw.program_id = $2
  AND pw.week_index = $3
  AND w.completed_at IS NOT NULL
  AND w.completed_at >= $4
  AND w.completed_at < $5
`

type CountCompletedProgramWorkoutSetsBetweenParams struct {
	UserID      uuid.UUID    `json:"user_id"`
	ProgramID   uuid.UUID    `json:"program_id"`
	WeekIndex   int32        `json:"week_index"`
	WindowStart sql.NullTime `json:"window_start"`
	WindowEnd   sql.NullTime `json:"window_end"`
}

func (q *Queries) CountCompletedProgramWorkoutSetsBetween(ctx context.Context, arg CountCompletedProgramWorkoutSetsBetweenParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countCompletedProgramWorkoutSetsBetween,
		arg.UserID,
		arg.ProgramID,
		arg.WeekIndex,
		arg.WindowStart,
		arg.WindowEnd,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countCompletedProgramWorkoutsBefore = `-- name: CountCompletedProgramWorkoutsBefore :one
SELECT COUNT(*)::int
FROM workouts w
JOIN program_sessions ps ON ps.id = w.program_session_id
JOIN program_weeks pw ON pw.id = ps.program_week_id
WHERE w.user_id = $1
  AND pw.program_id = $2
  AND w.completed_at IS NOT NULL
  AND w.completed_at < $3
`

type CountCompletedProgramWorkoutsBeforeParams struct {
	UserID     uuid.UUID    `json:"user_id"`
	ProgramID  uuid.UUID    `json:"program_id"`
	BeforeTime sql.NullTime `json:"before_time"`
}

func (q *Queries) CountCompletedProgramWorkoutsBefore(ctx context.Context, arg CountCompletedProgramWorkoutsBeforeParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countCompletedProgramWorkoutsBefore, arg.UserID, arg.ProgramID, arg.BeforeTime)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countCompletedProgramWorkoutsBetween = `-- name: CountCompletedProgramWorkoutsBetween :one
SELECT COUNT(*)::int
FROM workouts w
JOIN program_sessions ps ON ps.id = w.program_session_id
JOIN program_weeks pw ON pw.id = ps.program_week_id
WHERE w.user_id = $1
  AND pw.program_id = $2
  AND pw.week_index = $3
  AND w.completed_at IS NOT NULL
  AND w.completed_at >= $4
  AND w.completed_at < $5
`

type CountCompletedProgramWorkoutsBetweenParams struct {
	UserID      uuid.UUID    `json:"user_id"`
	ProgramID   uuid.UUID    `json:"program_id"`
	WeekIndex   int32        `json:"week_index"`
	WindowStart sql.NullTime `json:"window_start"`
	WindowEnd   sql.NullTime `json:"window_end"`
}

func (q *Queries) CountCompletedProgramWorkoutsBetween(ctx context.Context, arg CountCompletedProgramWorkoutsBetweenParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countCompletedProgramWorkoutsBetween,
		arg.UserID,
		arg.ProgramID,
		arg.WeekIndex,
		arg.WindowStart,
		arg.WindowEnd,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countHighRpeProgramWorkoutSetsBetween = `-- name: CountHighRpeProgramWorkoutSetsBetween :one
SELECT COUNT(ws.id)::int
FROM workouts w
JOIN program_sessions ps ON ps.id = w.program_session_id
JOIN program_weeks pw ON pw.id = ps.program_week_id
JOIN workout_exercises we ON we.workout_id = w.id
JOIN workout_sets ws ON ws.workout_exercise_id = we.id
WHERE w.user_id = $1
  AND pw.program_id = $2
  AND pw.week_index = $3
  AND w.completed_at IS NOT NULL
  AND w.completed_at >= $4
  AND w.completed_at < $5
  AND ws.rpe IS NOT NULL
  AND ws.rpe >= $6
`

type CountHighRpeProgramWorkoutSetsBetweenParams struct {
	UserID       uuid.UUID       `json:"user_id"`
	ProgramID    uuid.UUID       `json:"program_id"`
	WeekIndex    int32           `json:"week_index"`
	WindowStart  sql.NullTime    `json:"window_start"`
	WindowEnd    sql.NullTime    `json:"window_end"`
	RpeThreshold sql.NullFloat64 `json:"rpe_threshold"`
}

func (q *Queries) CountHighRpeProgramWorkoutSetsBetween(ctx context.Context, arg CountHighRpeProgramWorkoutSetsBetweenParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countHighRpeProgramWorkoutSetsBetween,
		arg.UserID,
		arg.ProgramID,
		arg.WeekIndex,
		arg.WindowStart,
		arg.WindowEnd,
		arg.RpeThreshold,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countProgramSessionsForWeek = `-- name: CountProgramSessionsForWeek :one
SELECT COUNT(*)::int
FROM program_sessions ps
JOIN program_weeks pw ON pw.id = ps.program_week_id
WHERE pw.program_id = $1
  AND pw.week_index = $2
`

type CountProgramSessionsForWeekParams struct {
	ProgramID uuid.UUID `json:"program_id"`
	WeekIndex int32     `json:"week_index"`
}

func (q *Queries) CountProgramSessionsForWeek(ctx context.Context, arg CountProgramSessionsForWeekParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countProgramSessionsForWeek, arg.ProgramID, arg.WeekIndex)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createWorkout = `-- name: CreateWorkout :one
INSERT INTO workouts (
    user_id,
    program_session_id,
    started_at,
    notes
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, user_id, program_session_id, started_at, completed_at, notes, created_at
`

type CreateWorkoutParams struct {
	UserID           uuid.UUID     `json:"user_id"`
	ProgramSessionID uuid.NullUUID `json:"program_session_id"`
	StartedAt        time.Time     `json:"started_at"`
	Notes            string        `json:"notes"`
}

func (q *Queries) CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error) {
	row := q.db.QueryRowContext(ctx, createWorkout,
		arg.UserID,
		arg.ProgramSessionID,
		arg.StartedAt,
		arg.Notes,
	)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProgramSessionID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkoutExercisesFromProgramSession = `-- name: CreateWorkoutExercisesFromProgramSession :many
INSERT INTO workout_exercises (
    workout_id,
    exercise_id,
    order_index,
    planned_json,
    actual_json
)
SELECT
    $1 AS workout_id,
    pse.exercise_id,
    pse.order_index,
    pse.prescription_json,
    '{}'::jsonb
FROM program_session_exercises pse
WHERE pse.program_session_id = $2
ORDER BY pse.order_index ASC
RETURNING id, workout_id, exercise_id, order_index, planned_json, actual_json, created_at
`

type CreateWorkoutExercisesFromProgramSessionParams struct {
	WorkoutID        uuid.UUID `json:"workout_id"`
	ProgramSessionID uuid.UUID `json:"program_session_id"`
}

func (q *Queries) CreateWorkoutExercisesFromProgramSession(ctx context.Context, arg CreateWorkoutExercisesFromProgramSessionParams) ([]WorkoutExercise, error) {
	rows, err := q.db.QueryContext(ctx, createWorkoutExercisesFromProgramSession, arg.WorkoutID, arg.ProgramSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkoutExercise{}
	for rows.Next() {
		var i WorkoutExercise
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutID,
			&i.ExerciseID,
			&i.OrderIndex,
			&i.PlannedJson,
			&i.ActualJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createWorkoutSetAutoIndexed = `-- name: CreateWorkoutSetAutoIndexed :one
WITH target_workout AS (
    SELECT w.id, w.completed_at
    FROM workouts w
    WHERE w.id = $1
      AND w.user_id = $2
    FOR UPDATE OF w
),
target_exercise AS (
    SELECT we.id
    FROM workout_exercises we
    JOIN target_workout tw ON tw.id = we.workout_id
    WHERE we.id = $3
    FOR UPDATE OF we
),
existing_set AS (
    SELECT
        ws.id,
        ws.workout_exercise_id,
        ws.set_index,
        ws.reps,
        ws.weight_kg,
        ws.rpe,
        ws.completed_at,
        ws.created_at,
        ws.idempotency_key
    FROM workout_sets ws
    JOIN target_exercise te ON te.id = ws.workout_exercise_id
    WHERE ws.idempotency_key = $4
    LIMIT 1
),
next_set_index AS (
    SELECT COALESCE(MAX(ws.set_index) + 1, 1) AS set_index
    FROM workout_sets ws
    JOIN target_exercise te ON te.id = ws.workout_exercise_id
),
inserted_set AS (
    INSERT INTO workout_sets (
        workout_exercise_id,
        set_index,
        reps,
        weight_kg,
        rpe,
        completed_at,
        idempotency_key
    )
    SELECT
        te.id,
        nsi.set_index,
        $5,
        $6,
        $7,
        $8,
        $4
    FROM target_exercise te
    CROSS JOIN next_set_index nsi
    WHERE NOT EXISTS (SELECT 1 FROM existing_set)
      AND EXISTS (
          SELECT 1
          FROM target_workout tw
          WHERE tw.completed_at IS NULL
      )
    RETURNING id, workout_exercise_id, set_index, reps, weight_kg, rpe, completed_at, created_at, idempotency_key
)
SELECT id, workout_exercise_id, set_index, reps, weight_kg, rpe, completed_at, created_at, idempotency_key
FROM inserted_set
UNION ALL
SELECT id, workout_exercise_id, set_index, reps, weight_kg, rpe, completed_at, created_at, idempotency_key
FROM existing_set
`

type CreateWorkoutSetAutoIndexedParams struct {
	WorkoutID         uuid.UUID       `json:"workout_id"`
	UserID            uuid.UUID       `json:"user_id"`
	WorkoutExerciseID uuid.UUID       `json:"workout_exercise_id"`
	IdempotencyKey    sql.NullString  `json:"idempotency_key"`
	Reps              int32           `json:"reps"`
	WeightKg          float64         `json:"weight_kg"`
	Rpe               sql.NullFloat64 `json:"rpe"`
	CompletedAt       time.Time       `json:"completed_at"`
}

type CreateWorkoutSetAutoIndexedRow struct {
	ID                uuid.UUID       `json:"id"`
	WorkoutExerciseID uuid.UUID       `json:"workout_exercise_id"`
	SetIndex          int32           `json:"set_index"`
	Reps              int32           `json:"reps"`
	WeightKg          float64         `json:"weight_kg"`
	Rpe               sql.NullFloat64 `json:"rpe"`
	CompletedAt       time.Time       `json:"completed_at"`
	CreatedAt         time.Time       `json:"created_at"`
	IdempotencyKey    sql.NullString  `json:"idempotency_key"`
}

func (q *Queries) CreateWorkoutSetAutoIndexed(ctx context.Context, arg CreateWorkoutSetAutoIndexedParams) (CreateWorkoutSetAutoIndexedRow, error) {
	row := q.db.QueryRowContext(ctx, createWorkoutSetAutoIndexed,
		arg.WorkoutID,
		arg.UserID,
		arg.WorkoutExerciseID,
		arg.IdempotencyKey,
		arg.Reps,
		arg.WeightKg,
		arg.Rpe,
		arg.CompletedAt,
	)
	var i CreateWorkoutSetAutoIndexedRow
	err := row.Scan(
		&i.ID,
		&i.WorkoutExerciseID,
		&i.SetIndex,
		&i.Reps,
		&i.WeightKg,
		&i.Rpe,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getProgramIDByProgramSessionID = `-- name: GetProgramIDByProgramSessionID :one
SELECT pw.program_id
FROM program_sessions ps
JOIN program_weeks pw ON pw.id = ps.program_week_id
WHERE ps.id = $1
LIMIT 1
`

func (q *Queries) GetProgramIDByProgramSessionID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getProgramIDByProgramSessionID, id)
	var program_id uuid.UUID
	err := row.Scan(&program_id)
	return program_id, err
}

const getProgramSessionByID = `-- name: GetProgramSessionByID :one
SELECT id, program_week_id, day_of_week, name, created_at
FROM program_sessions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProgramSessionByID(ctx context.Context, id uuid.UUID) (ProgramSession, error) {
	row := q.db.QueryRowContext(ctx, getProgramSessionByID, id)
	var i ProgramSession
	err := row.Scan(
		&i.ID,
		&i.ProgramWeekID,
		&i.DayOfWeek,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkoutByIDAndUserID = `-- name: GetWorkoutByIDAndUserID :one
SELECT id, user_id, program_session_id, started_at, completed_at, notes, created_at
FROM workouts
WHERE id = $1
  AND user_id = $2
LIMIT 1
`

type GetWorkoutByIDAndUserIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetWorkoutByIDAndUserID(ctx context.Context, arg GetWorkoutByIDAndUserIDParams) (Workout, error) {
	row := q.db.QueryRowContext(ctx, getWorkoutByIDAndUserID, arg.ID, arg.UserID)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProgramSessionID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listPreviousWorkoutSetsByWorkoutID = `-- name: ListPreviousWorkoutSetsByWorkoutID :many
WITH current_workout AS (
    SELECT w.id, w.user_id, w.started_at
    FROM workouts w
    WHERE w.id = $1
    LIMIT 1
),
current_exercises AS (
    SELECT
        we.id AS target_workout_exercise_id,
        we.exercise_id
    FROM workout_exercises we
    WHERE we.workout_id = $1
),
latest_previous_workout AS (
    SELECT
        ce.target_workout_exercise_id,
        pw.id AS previous_workout_id,
        pw.completed_at AS previous_workout_completed_at,
        ROW_NUMBER() OVER (
            PARTITION BY ce.target_workout_exercise_id
            ORDER BY pw.completed_at DESC, pw.id DESC
        ) AS rank_index
    FROM current_exercises ce
    JOIN workout_exercises pwe ON pwe.exercise_id = ce.exercise_id
    JOIN workouts pw ON pw.id = pwe.workout_id
    JOIN current_workout cw ON cw.user_id = pw.user_id
    WHERE pw.completed_at IS NOT NULL
      AND pw.id <> cw.id
      AND (pw.started_at, pw.id) < (cw.started_at, cw.id)
),
selected_previous_workout AS (
    SELECT
        target_workout_exercise_id,
        previous_workout_id,
        previous_workout_completed_at
    FROM latest_previous_workout
    WHERE rank_index = 1
),
selected_previous_exercise AS (
    SELECT
        spw.target_workout_exercise_id,
        pwe.id AS previous_workout_exercise_id,
        spw.previous_workout_id,
        spw.previous_workout_completed_at
    FROM selected_previous_workout spw
    JOIN current_exercises ce
        ON ce.target_workout_exercise_id = spw.target_workout_exercise_id
    JOIN LATERAL (
        SELECT previous_we.id
        FROM workout_exercises previous_we
        WHERE previous_we.workout_id = spw.previous_workout_id
          AND previous_we.exercise_id = ce.exercise_id
        ORDER BY previous_we.order_index ASC
        LIMIT 1
    ) pwe ON TRUE
)
SELECT
    spe.target_workout_exercise_id,
    spe.previous_workout_id,
    spe.previous_workout_completed_at,
    ws.set_index,
    ws.reps,
    ws.weight_kg,
    ws.rpe
FROM selected_previous_exercise spe
JOIN workout_sets ws ON ws.workout_exercise_id = spe.previous_workout_exercise_id
ORDER BY spe.target_workout_exercise_id ASC, ws.set_index ASC
`

type ListPreviousWorkoutSetsByWorkoutIDRow struct {
	TargetWorkoutExerciseID    uuid.UUID       `json:"target_workout_exercise_id"`
	PreviousWorkoutID          uuid.UUID       `json:"previous_workout_id"`
	PreviousWorkoutCompletedAt sql.NullTime    `json:"previous_workout_completed_at"`
	SetIndex                   int32           `json:"set_index"`
	Reps                       int32           `json:"reps"`
	WeightKg                   float64         `json:"weight_kg"`
	Rpe                        sql.NullFloat64 `json:"rpe"`
}

func (q *Queries) ListPreviousWorkoutSetsByWorkoutID(ctx context.Context, workoutID uuid.UUID) ([]ListPreviousWorkoutSetsByWorkoutIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listPreviousWorkoutSetsByWorkoutID, workoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPreviousWorkoutSetsByWorkoutIDRow{}
	for rows.Next() {
		var i ListPreviousWorkoutSetsByWorkoutIDRow
		if err := rows.Scan(
			&i.TargetWorkoutExerciseID,
			&i.PreviousWorkoutID,
			&i.PreviousWorkoutCompletedAt,
			&i.SetIndex,
			&i.Reps,
			&i.WeightKg,
			&i.Rpe,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutExercisesByWorkoutID = `-- name: ListWorkoutExercisesByWorkoutID :many
SELECT
    we.id,
    we.workout_id,
    we.exercise_id,
    we.order_index,
    we.planned_json,
    we.actual_json,
    we.created_at,
    e.slug AS exercise_slug,
    e.name AS exercise_name
FROM workout_exercises we
JOIN exercises e ON e.id = we.exercise_id
WHERE we.workout_id = $1
ORDER BY we.order_index ASC
`

type ListWorkoutExercisesByWorkoutIDRow struct {
	ID           uuid.UUID       `json:"id"`
	WorkoutID    uuid.UUID       `json:"workout_id"`
	ExerciseID   uuid.UUID       `json:"exercise_id"`
	OrderIndex   int32           `json:"order_index"`
	PlannedJson  json.RawMessage `json:"planned_json"`
	ActualJson   json.RawMessage `json:"actual_json"`
	CreatedAt    time.Time       `json:"created_at"`
	ExerciseSlug string          `json:"exercise_slug"`
	ExerciseName string          `json:"exercise_name"`
}

func (q *Queries) ListWorkoutExercisesByWorkoutID(ctx context.Context, workoutID uuid.UUID) ([]ListWorkoutExercisesByWorkoutIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkoutExercisesByWorkoutID, workoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkoutExercisesByWorkoutIDRow{}
	for rows.Next() {
		var i ListWorkoutExercisesByWorkoutIDRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutID,
			&i.ExerciseID,
			&i.OrderIndex,
			&i.PlannedJson,
			&i.ActualJson,
			&i.CreatedAt,
			&i.ExerciseSlug,
			&i.ExerciseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutHistory = `-- name: ListWorkoutHistory :many
SELECT id, user_id, program_session_id, started_at, completed_at, notes, created_at
FROM workouts
WHERE user_id = $1
  AND (
    NOT $2::boolean
    OR (started_at, id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY started_at DESC, id DESC
LIMIT $5
`

type ListWorkoutHistoryParams struct {
	UserID          uuid.UUID `json:"user_id"`
	HasCursor       bool      `json:"has_cursor"`
	CursorStartedAt time.Time `json:"cursor_started_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	LimitCount      int32     `json:"limit_count"`
}

func (q *Queries) ListWorkoutHistory(ctx context.Context, arg ListWorkoutHistoryParams) ([]Workout, error) {
	rows, err := q.db.QueryContext(ctx, listWorkoutHistory,
		arg.UserID,
		arg.HasCursor,
		arg.CursorStartedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workout{}
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProgramSessionID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutSetsByWorkoutID = `-- name: ListWorkoutSetsByWorkoutID :many
SELECT
    ws.id,
    ws.workout_exercise_id,
    ws.set_index,
    ws.reps,
    ws.weight_kg,
    ws.rpe,
    ws.completed_at,
    ws.created_at,
    ws.idempotency_key
FROM workout_sets ws
JOIN workout_exercises we ON we.id = ws.workout_exercise_id
WHERE we.workout_id = $1
ORDER BY we.order_index ASC, ws.set_index ASC
`

func (q *Queries) ListWorkoutSetsByWorkoutID(ctx context.Context, workoutID uuid.UUID) ([]WorkoutSet, error) {
	rows, err := q.db.QueryContext(ctx, listWorkoutSetsByWorkoutID, workoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkoutSet{}
	for rows.Next() {
		var i WorkoutSet
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutExerciseID,
			&i.SetIndex,
			&i.Reps,
			&i.WeightKg,
			&i.Rpe,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.IdempotencyKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
